// Code generated by "stringer -type Simple"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConstType-0]
	_ = x[NilType-1]
	_ = x[FuncType-2]
	_ = x[AnyType-3]
	_ = x[ErrorType-4]
}

const _Simple_name = "ConstTypeNilTypeFuncTypeAnyTypeErrorType"

var _Simple_index = [...]uint8{0, 9, 16, 24, 31, 40}

func (i Simple) String() string {
	if i < 0 || i >= Simple(len(_Simple_index)-1) {
		return "Simple(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Simple_name[_Simple_index[i]:_Simple_index[i+1]]
}
