// Code generated by goyacc -l -o ruby.go ruby.y. DO NOT EDIT.
package parser

import (
	__yyfmt__ "fmt"
	"strings"
)

func setRoot(yylex yyLexer, nodes []Node) {
	p := yylex.(*Lexer).Root
	for _, n := range nodes {
		p.AddStatement(n)
	}
}

func root(yylex yyLexer) *Root {
	return yylex.(*Lexer).Root
}

type yySymType struct {
	yys       int
	args      ArgsNode
	blk       *Block
	body      *Body
	kv        *KeyValuePair
	kvs       []*KeyValuePair
	meth      *Method
	node      Node
	node_list Statements
	param     *Param
	params    []*Param
	root      *Root
	regexp    string
	when      *WhenNode
	whens     []*WhenNode
	str       string
}

const LOWEST = 57346
const ASSIGN = 57347
const MODASSIGN = 57348
const MULASSIGN = 57349
const ADDASSIGN = 57350
const SUBASSIGN = 57351
const DIVASSIGN = 57352
const QMARK = 57353
const COLON = 57354
const DOT2 = 57355
const DOT3 = 57356
const LOGICALOR = 57357
const LOGICALAND = 57358
const SPACESHIP = 57359
const EQ = 57360
const NEQ = 57361
const MATCH = 57362
const NOTMATCH = 57363
const GT = 57364
const GTE = 57365
const LT = 57366
const LTE = 57367
const AND = 57368
const PIPE = 57369
const CARET = 57370
const LSHIFT = 57371
const RSHIFT = 57372
const PLUS = 57373
const MINUS = 57374
const ASTERISK = 57375
const SLASH = 57376
const MODULO = 57377
const UNARY_NUM = 57378
const POW = 57379
const BANG = 57380
const NIL = 57381
const SYMBOL = 57382
const STRING = 57383
const INT = 57384
const FLOAT = 57385
const TRUE = 57386
const FALSE = 57387
const CLASS = 57388
const MODULE = 57389
const DEF = 57390
const END = 57391
const IF = 57392
const IF_MOD = 57393
const UNLESS = 57394
const UNLESS_MOD = 57395
const BEGIN = 57396
const RESCUE = 57397
const RESCUE_MOD = 57398
const THEN = 57399
const ELSE = 57400
const WHILE = 57401
const WHILE_MOD = 57402
const RETURN = 57403
const YIELD = 57404
const SELF = 57405
const CONSTANT = 57406
const ENSURE = 57407
const ELSIF = 57408
const CASE = 57409
const WHEN = 57410
const UNTIL = 57411
const UNTIL_MOD = 57412
const FOR = 57413
const BREAK = 57414
const NEXT = 57415
const SUPER = 57416
const ALIAS = 57417
const DO = 57418
const PRIVATE = 57419
const PROTECTED = 57420
const IVAR = 57421
const CVAR = 57422
const GVAR = 57423
const METHODIDENT = 57424
const IDENT = 57425
const COMMENT = 57426
const LABEL = 57427
const DOT = 57428
const LBRACE = 57429
const RBRACE = 57430
const NEWLINE = 57431
const COMMA = 57432
const STRINGBEG = 57433
const STRINGEND = 57434
const INTERPBEG = 57435
const INTERPEND = 57436
const STRINGBODY = 57437
const REGEXBEG = 57438
const REGEXEND = 57439
const REGEXPOPT = 57440
const RAWSTRINGBEG = 57441
const RAWSTRINGEND = 57442
const WORDSBEG = 57443
const RAWWORDSBEG = 57444
const SEMICOLON = 57445
const LBRACKET = 57446
const LBRACKETSTART = 57447
const RBRACKET = 57448
const LPAREN = 57449
const LPARENSTART = 57450
const RPAREN = 57451
const HASHROCKET = 57452
const SCOPE = 57453

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LOWEST",
	"ASSIGN",
	"MODASSIGN",
	"MULASSIGN",
	"ADDASSIGN",
	"SUBASSIGN",
	"DIVASSIGN",
	"QMARK",
	"COLON",
	"DOT2",
	"DOT3",
	"LOGICALOR",
	"LOGICALAND",
	"SPACESHIP",
	"EQ",
	"NEQ",
	"MATCH",
	"NOTMATCH",
	"GT",
	"GTE",
	"LT",
	"LTE",
	"AND",
	"PIPE",
	"CARET",
	"LSHIFT",
	"RSHIFT",
	"PLUS",
	"MINUS",
	"ASTERISK",
	"SLASH",
	"MODULO",
	"UNARY_NUM",
	"POW",
	"BANG",
	"NIL",
	"SYMBOL",
	"STRING",
	"INT",
	"FLOAT",
	"TRUE",
	"FALSE",
	"CLASS",
	"MODULE",
	"DEF",
	"END",
	"IF",
	"IF_MOD",
	"UNLESS",
	"UNLESS_MOD",
	"BEGIN",
	"RESCUE",
	"RESCUE_MOD",
	"THEN",
	"ELSE",
	"WHILE",
	"WHILE_MOD",
	"RETURN",
	"YIELD",
	"SELF",
	"CONSTANT",
	"ENSURE",
	"ELSIF",
	"CASE",
	"WHEN",
	"UNTIL",
	"UNTIL_MOD",
	"FOR",
	"BREAK",
	"NEXT",
	"SUPER",
	"ALIAS",
	"DO",
	"PRIVATE",
	"PROTECTED",
	"IVAR",
	"CVAR",
	"GVAR",
	"METHODIDENT",
	"IDENT",
	"COMMENT",
	"LABEL",
	"DOT",
	"LBRACE",
	"RBRACE",
	"NEWLINE",
	"COMMA",
	"STRINGBEG",
	"STRINGEND",
	"INTERPBEG",
	"INTERPEND",
	"STRINGBODY",
	"REGEXBEG",
	"REGEXEND",
	"REGEXPOPT",
	"RAWSTRINGBEG",
	"RAWSTRINGEND",
	"WORDSBEG",
	"RAWWORDSBEG",
	"SEMICOLON",
	"LBRACKET",
	"LBRACKETSTART",
	"RBRACKET",
	"LPAREN",
	"LPARENSTART",
	"RPAREN",
	"HASHROCKET",
	"SCOPE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 12,
	5, 40,
	6, 199,
	7, 199,
	8, 199,
	9, 199,
	10, 199,
	90, 37,
	-2, 197,
	-1, 13,
	5, 41,
	6, 200,
	7, 200,
	8, 200,
	9, 200,
	10, 200,
	90, 38,
	-2, 198,
	-1, 20,
	36, 231,
	38, 231,
	39, 231,
	40, 231,
	42, 231,
	43, 231,
	44, 231,
	45, 231,
	46, 231,
	48, 231,
	50, 231,
	52, 231,
	59, 231,
	62, 231,
	63, 231,
	64, 231,
	67, 231,
	69, 231,
	79, 231,
	80, 231,
	81, 231,
	82, 231,
	83, 231,
	85, 231,
	87, 231,
	91, 231,
	96, 231,
	99, 231,
	101, 231,
	102, 231,
	105, 231,
	107, 231,
	108, 231,
	-2, 188,
	-1, 23,
	36, 232,
	38, 232,
	39, 232,
	40, 232,
	42, 232,
	43, 232,
	44, 232,
	45, 232,
	46, 232,
	48, 232,
	50, 232,
	52, 232,
	59, 232,
	62, 232,
	63, 232,
	64, 232,
	67, 232,
	69, 232,
	79, 232,
	80, 232,
	81, 232,
	82, 232,
	83, 232,
	85, 232,
	87, 232,
	91, 232,
	96, 232,
	99, 232,
	101, 232,
	102, 232,
	105, 232,
	107, 232,
	108, 232,
	-2, 191,
	-1, 29,
	86, 143,
	104, 143,
	111, 143,
	-2, 95,
	-1, 120,
	5, 37,
	90, 37,
	-2, 197,
	-1, 121,
	5, 38,
	90, 38,
	-2, 198,
	-1, 130,
	5, 40,
	6, 199,
	7, 199,
	8, 199,
	9, 199,
	10, 199,
	-2, 197,
	-1, 131,
	5, 41,
	6, 200,
	7, 200,
	8, 200,
	9, 200,
	10, 200,
	-2, 198,
	-1, 212,
	90, 115,
	-2, 118,
	-1, 219,
	90, 102,
	-2, 105,
	-1, 227,
	5, 43,
	-2, 231,
	-1, 230,
	13, 0,
	14, 0,
	-2, 70,
	-1, 231,
	13, 0,
	14, 0,
	-2, 71,
	-1, 241,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	-2, 83,
	-1, 242,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	-2, 85,
	-1, 243,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	-2, 86,
	-1, 244,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	-2, 87,
	-1, 245,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	-2, 88,
	-1, 322,
	5, 42,
	90, 39,
	-2, 157,
	-1, 371,
	90, 116,
	-2, 120,
	-1, 374,
	5, 39,
	90, 39,
	-2, 157,
	-1, 375,
	5, 42,
	-2, 157,
}

const yyPrivate = 57344

const yyLast = 1502

var yyAct = [...]int{
	18, 260, 364, 322, 378, 316, 379, 132, 14, 148,
	307, 311, 224, 310, 312, 309, 289, 164, 29, 308,
	141, 168, 279, 381, 72, 269, 259, 122, 275, 74,
	263, 356, 254, 127, 330, 84, 17, 91, 123, 73,
	169, 138, 138, 138, 145, 254, 216, 14, 372, 5,
	391, 140, 138, 138, 91, 258, 262, 92, 14, 317,
	302, 165, 92, 253, 301, 172, 298, 390, 304, 366,
	92, 77, 90, 160, 265, 268, 76, 125, 51, 92,
	376, 14, 274, 138, 219, 223, 367, 60, 161, 225,
	75, 138, 265, 264, 230, 231, 232, 233, 234, 235,
	236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
	246, 247, 248, 249, 250, 251, 315, 51, 318, 209,
	217, 217, 51, 51, 51, 51, 51, 255, 51, 129,
	10, 222, 146, 218, 218, 363, 324, 128, 7, 320,
	306, 146, 170, 377, 138, 273, 138, 175, 252, 300,
	301, 51, 298, 133, 131, 13, 51, 51, 51, 51,
	51, 51, 51, 261, 14, 257, 14, 319, 202, 10,
	138, 267, 272, 204, 121, 337, 266, 7, 282, 175,
	10, 278, 296, 280, 288, 280, 318, 285, 7, 130,
	12, 295, 281, 203, 13, 152, 215, 9, 340, 161,
	369, 291, 382, 10, 286, 13, 151, 211, 382, 120,
	380, 7, 77, 10, 10, 355, 229, 76, 283, 77,
	287, 220, 220, 351, 76, 386, 323, 4, 13, 12,
	78, 75, 79, 291, 51, 271, 51, 163, 75, 80,
	12, 343, 154, 154, 154, 154, 154, 171, 228, 81,
	326, 144, 327, 281, 138, 61, 404, 223, 223, 138,
	401, 388, 384, 12, 348, 138, 328, 134, 261, 138,
	138, 329, 346, 345, 138, 138, 154, 154, 154, 154,
	77, 221, 149, 335, 14, 76, 10, 14, 10, 332,
	14, 214, 138, 317, 7, 332, 7, 339, 334, 75,
	14, 201, 341, 167, 222, 347, 173, 352, 174, 358,
	354, 13, 365, 13, 350, 294, 156, 361, 200, 138,
	357, 138, 223, 137, 142, 138, 78, 317, 79, 100,
	323, 323, 374, 375, 335, 80, 114, 362, 338, 70,
	71, 342, 175, 277, 344, 81, 12, 293, 12, 373,
	397, 383, 318, 368, 51, 321, 256, 51, 217, 14,
	51, 83, 33, 82, 158, 212, 137, 1, 126, 138,
	51, 218, 139, 398, 400, 395, 387, 393, 50, 394,
	393, 396, 119, 280, 315, 389, 318, 138, 392, 395,
	14, 150, 138, 166, 3, 14, 157, 407, 349, 51,
	290, 97, 98, 99, 406, 100, 10, 313, 323, 10,
	409, 276, 10, 385, 7, 411, 14, 7, 305, 314,
	7, 226, 10, 210, 135, 408, 270, 325, 19, 51,
	7, 13, 280, 11, 13, 6, 2, 13, 53, 36,
	35, 153, 155, 31, 403, 159, 43, 13, 37, 405,
	30, 10, 115, 117, 116, 118, 360, 38, 51, 220,
	51, 34, 136, 54, 147, 51, 12, 55, 57, 12,
	410, 284, 12, 147, 147, 205, 206, 207, 208, 8,
	292, 10, 12, 162, 303, 58, 51, 299, 297, 7,
	56, 359, 103, 101, 102, 109, 110, 95, 96, 97,
	98, 99, 176, 100, 213, 213, 13, 95, 96, 97,
	98, 99, 10, 100, 0, 0, 0, 10, 0, 0,
	7, 0, 0, 0, 0, 7, 101, 102, 109, 110,
	95, 96, 97, 98, 99, 0, 100, 13, 10, 0,
	0, 12, 13, 0, 0, 0, 7, 331, 0, 0,
	0, 142, 333, 0, 0, 0, 336, 142, 85, 86,
	87, 88, 89, 13, 0, 0, 0, 147, 0, 0,
	0, 0, 12, 0, 137, 0, 0, 12, 402, 0,
	0, 0, 0, 62, 0, 32, 25, 63, 0, 70,
	71, 27, 28, 49, 0, 59, 0, 44, 12, 45,
	0, 370, 0, 371, 0, 0, 46, 336, 52, 42,
	26, 23, 0, 0, 48, 0, 47, 0, 0, 0,
	0, 0, 0, 0, 15, 16, 21, 24, 22, 69,
	20, 0, 0, 0, 41, 0, 202, 0, 64, 0,
	0, 0, 0, 68, 0, 0, 66, 0, 65, 67,
	0, 399, 40, 0, 62, 39, 32, 25, 63, 0,
	70, 71, 27, 28, 49, 0, 59, 0, 44, 331,
	45, 0, 0, 0, 0, 0, 0, 46, 0, 52,
	42, 26, 23, 0, 0, 48, 0, 47, 109, 110,
	95, 96, 97, 98, 99, 0, 100, 21, 24, 22,
	69, 20, 77, 0, 0, 41, 0, 76, 0, 64,
	0, 0, 0, 353, 68, 0, 0, 66, 0, 65,
	67, 75, 0, 40, 0, 62, 39, 32, 25, 63,
	0, 70, 71, 27, 28, 49, 0, 59, 0, 44,
	0, 45, 0, 0, 0, 0, 0, 0, 46, 0,
	52, 42, 26, 23, 0, 0, 48, 0, 47, 0,
	0, 0, 0, 0, 0, 0, 15, 16, 21, 24,
	22, 69, 20, 0, 0, 0, 41, 0, 0, 0,
	64, 0, 0, 0, 0, 68, 0, 0, 66, 0,
	65, 67, 0, 0, 40, 0, 62, 39, 32, 25,
	63, 0, 70, 71, 27, 28, 49, 0, 59, 0,
	44, 0, 45, 0, 0, 0, 0, 0, 0, 46,
	0, 0, 124, 26, 23, 0, 0, 48, 0, 47,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 21,
	24, 22, 69, 20, 0, 143, 0, 41, 0, 261,
	0, 64, 0, 0, 0, 0, 68, 0, 0, 66,
	0, 65, 67, 0, 0, 40, 0, 62, 39, 32,
	25, 63, 0, 70, 71, 27, 28, 49, 0, 59,
	0, 44, 0, 45, 0, 0, 0, 0, 0, 0,
	46, 0, 0, 124, 26, 23, 0, 0, 48, 0,
	47, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	21, 24, 22, 69, 20, 0, 143, 0, 41, 0,
	0, 0, 64, 0, 0, 0, 0, 68, 0, 0,
	66, 0, 65, 67, 0, 0, 40, 0, 169, 39,
	62, 0, 32, 25, 63, 0, 70, 71, 27, 28,
	49, 0, 59, 0, 44, 0, 45, 0, 0, 0,
	0, 0, 0, 46, 0, 0, 124, 26, 23, 0,
	0, 48, 0, 47, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 21, 24, 22, 69, 20, 0, 143,
	0, 41, 0, 0, 0, 64, 0, 0, 0, 0,
	68, 0, 0, 66, 0, 65, 67, 0, 0, 40,
	0, 145, 39, 62, 0, 32, 25, 63, 0, 70,
	71, 27, 28, 49, 0, 59, 0, 44, 0, 45,
	0, 0, 0, 0, 0, 0, 46, 0, 0, 124,
	26, 23, 0, 0, 48, 0, 47, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 21, 24, 22, 69,
	20, 0, 143, 0, 41, 0, 0, 0, 64, 0,
	0, 0, 0, 68, 0, 0, 66, 0, 65, 67,
	0, 0, 40, 0, 62, 39, 32, 25, 63, 0,
	70, 71, 27, 28, 49, 0, 59, 0, 44, 0,
	45, 0, 0, 0, 0, 0, 0, 46, 0, 52,
	42, 26, 23, 0, 0, 48, 0, 47, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 21, 24, 22,
	69, 20, 0, 0, 0, 41, 0, 0, 0, 64,
	0, 0, 0, 0, 68, 0, 0, 66, 0, 65,
	67, 0, 0, 40, 0, 62, 39, 32, 25, 63,
	0, 70, 71, 27, 28, 49, 0, 59, 0, 44,
	0, 45, 0, 0, 0, 0, 0, 0, 46, 0,
	0, 124, 26, 23, 0, 0, 48, 0, 47, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 21, 24,
	22, 69, 20, 0, 0, 0, 41, 0, 0, 0,
	64, 0, 0, 0, 0, 68, 0, 0, 66, 0,
	65, 67, 62, 0, 40, 25, 63, 39, 70, 71,
	27, 28, 49, 0, 59, 0, 44, 0, 45, 0,
	0, 0, 0, 0, 0, 46, 0, 0, 124, 26,
	23, 0, 0, 48, 0, 47, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 21, 24, 22, 69, 20,
	0, 0, 0, 41, 0, 0, 0, 64, 0, 0,
	0, 0, 68, 0, 0, 66, 0, 65, 67, 0,
	0, 40, 0, 113, 39, 93, 94, 112, 111, 104,
	105, 106, 107, 108, 115, 117, 116, 118, 103, 101,
	102, 109, 110, 95, 96, 97, 98, 99, 0, 100,
	182, 183, 190, 184, 185, 186, 187, 188, 189, 181,
	179, 180, 191, 192, 193, 194, 195, 196, 197, 0,
	198, 199, 182, 183, 190, 184, 185, 186, 187, 188,
	189, 181, 179, 180, 191, 192, 193, 194, 195, 196,
	197, 0, 198, 199, 0, 0, 0, 178, 0, 0,
	0, 261, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 69, 177, 0, 0, 178,
	115, 117, 116, 118, 103, 101, 102, 109, 110, 95,
	96, 97, 98, 99, 0, 100, 0, 69, 227, 113,
	0, 93, 94, 112, 111, 104, 105, 106, 107, 108,
	115, 117, 116, 118, 103, 101, 102, 109, 110, 95,
	96, 97, 98, 99, 0, 100, 112, 111, 104, 105,
	106, 107, 108, 115, 117, 116, 118, 103, 101, 102,
	109, 110, 95, 96, 97, 98, 99, 0, 100, 111,
	104, 105, 106, 107, 108, 115, 117, 116, 118, 103,
	101, 102, 109, 110, 95, 96, 97, 98, 99, 0,
	100, 104, 105, 106, 107, 108, 115, 117, 116, 118,
	103, 101, 102, 109, 110, 95, 96, 97, 98, 99,
	0, 100,
}

var yyPact = [...]int{
	689, -1000, -1000, -13, 275, -1000, 358, 356, -1000, -1000,
	552, -1000, -1000, -1000, -32, -1000, -1000, -1000, 1398, 1186,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 430, 1119, 63, -1000, -1000, -1000, -1000, -1000, 689,
	1119, 977, 904, 119, 1048, 1048, 1048, 1048, 618, 173,
	689, 831, 977, -1000, -1000, -1000, -1000, -30, -1000, 1303,
	-1000, -1000, 297, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 547, -1000, -1000, 109, 84, 1048, 1048,
	1048, 1048, 1048, 1048, 1048, -1000, -1000, -1000, -1000, -1000,
	977, 1325, 152, 1119, 1119, 1119, 1119, 1119, 1119, 1119,
	1119, 1119, 1119, 1119, 1119, 1119, 1119, 1119, 1119, 1119,
	1119, 1119, 1119, 1119, 1119, -1000, -1000, -1000, -1000, 58,
	-1000, -1000, -41, -1000, -63, -67, 1119, -1000, 351, 552,
	-1000, -1000, -49, -1000, 179, -50, 3, -1000, 1398, 88,
	-15, -1000, -85, 1119, -1000, 760, -1000, 55, -8, -85,
	-1000, 316, 316, 196, -1000, 196, 689, 128, 689, -13,
	133, 79, 323, -1000, 266, -1000, -13, -1000, -1000, 977,
	-1000, 57, -40, -29, 33, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 275, -1000, 78, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 49, -1000, -1000, -1000, -1000, -1000, 1398,
	350, -1000, -1000, 1398, 74, -1000, 46, -1000, -67, -1000,
	1421, 1421, 368, 368, 292, 292, 292, 292, 659, 659,
	499, 1368, 1368, 1368, 1368, 1368, 476, 476, 1464, 1443,
	1282, 466, -1000, 977, 1303, 466, 1119, 1119, 977, -1000,
	-75, -1000, -1000, -1000, 1119, -1000, -1000, -1000, 977, 1119,
	-1000, 74, -1000, 977, 977, 87, 689, 115, 253, 689,
	184, -1000, 689, 224, -1000, -1000, -1000, 223, 133, 215,
	165, 1119, 689, 151, -1000, -1000, -78, -1000, -1000, -1000,
	-1000, 1186, -1000, -1000, -1000, -1000, 301, -13, 45, -21,
	-1000, -1000, -1000, -4, -1000, 348, -1000, 117, 1119, -1000,
	1119, 1048, -1000, -58, 977, -1000, -1000, 337, 74, 74,
	-1000, -1000, -1000, -1000, -1000, -8, -85, -1000, -1000, 53,
	-1000, -1000, 144, -1000, 150, -1000, -1000, 213, -1000, -1000,
	-1000, 689, -1000, 135, 212, -13, -1000, -27, -54, -1000,
	-1000, 74, -1000, 301, -1000, -1000, 267, 101, 1119, -1000,
	-1000, -1000, -1000, 1119, -1000, -1000, -1000, 115, 211, -1000,
	1048, -1000, 689, 207, -1000, -1000, 1119, 689, -1000, -1000,
	-1000, 977, -1000, -1000, -21, -1000, -1000, 348, -1000, -1000,
	1398, -1000, 196, -1000, -1000, -1000, 74, -1000, 689, -1000,
	144, -1000,
}

var yyPgo = [...]int{
	0, 77, 87, 26, 502, 248, 22, 29, 336, 3,
	490, 488, 247, 487, 485, 484, 483, 35, 480, 479,
	471, 468, 467, 463, 189, 154, 255, 197, 0, 18,
	461, 137, 457, 129, 7, 396, 49, 196, 450, 36,
	448, 316, 46, 282, 446, 227, 4, 6, 23, 443,
	440, 439, 362, 438, 61, 393, 436, 435, 433, 428,
	421, 89, 12, 21, 427, 424, 251, 207, 423, 11,
	5, 14, 419, 418, 10, 19, 411, 407, 2, 13,
	15, 17, 400, 16, 398, 28, 391, 378, 20, 9,
	372, 367, 24, 39, 1, 30,
}

var yyR1 = [...]int{
	0, 91, 56, 81, 54, 55, 55, 55, 45, 45,
	45, 45, 45, 45, 45, 45, 45, 45, 36, 36,
	37, 37, 27, 27, 35, 41, 39, 1, 38, 38,
	38, 57, 58, 58, 52, 59, 59, 53, 53, 53,
	31, 31, 31, 31, 16, 5, 5, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 8, 8, 8, 8,
	49, 49, 43, 65, 65, 42, 63, 64, 64, 62,
	62, 62, 61, 61, 61, 60, 60, 68, 68, 66,
	67, 29, 29, 29, 29, 29, 29, 29, 29, 29,
	29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
	29, 29, 29, 34, 6, 6, 6, 20, 20, 46,
	46, 47, 47, 76, 76, 44, 44, 44, 86, 86,
	85, 83, 82, 84, 84, 84, 30, 30, 50, 51,
	21, 21, 10, 10, 11, 12, 12, 12, 13, 40,
	14, 15, 87, 22, 23, 23, 26, 26, 24, 24,
	24, 24, 24, 25, 25, 25, 25, 32, 32, 33,
	33, 18, 18, 73, 73, 79, 79, 78, 78, 74,
	74, 74, 74, 74, 69, 75, 75, 70, 70, 77,
	77, 71, 80, 80, 72, 90, 90, 89, 89, 88,
	88, 2, 2, 2, 92, 92, 94, 94, 3, 9,
	95, 95, 95, 7, 7, 7, 7, 93, 93, 48,
	17, 17, 17, 17, 17, 19, 19,
}

var yyR2 = [...]int{
	0, 1, 2, 1, 2, 0, 1, 3, 3, 3,
	3, 3, 1, 3, 3, 3, 1, 1, 3, 3,
	1, 1, 1, 1, 1, 2, 1, 1, 2, 2,
	2, 1, 1, 2, 1, 2, 3, 1, 1, 4,
	1, 1, 4, 3, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 3, 3,
	3, 3, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 1, 3, 3, 3, 3, 2,
	3, 3, 3, 3, 6, 1, 1, 1, 1, 1,
	3, 3, 1, 0, 2, 1, 3, 0, 1, 0,
	1, 2, 1, 1, 3, 1, 3, 1, 1, 1,
	3, 1, 1, 1, 1, 1, 3, 3, 3, 3,
	4, 3, 1, 1, 2, 6, 6, 4, 4, 5,
	4, 5, 3, 1, 1, 1, 2, 1, 1, 1,
	5, 1, 2, 0, 3, 2, 4, 4, 3, 3,
	2, 2, 4, 1, 2, 1, 1, 1, 3, 3,
	1, 1, 1, 1, 1, 2, 2, 0, 3, 3,
	1, 1, 3, 1, 1, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 0, 3, 3, 2, 1, 1, 2, 0, 4,
	2, 2, 1, 0, 1, 1, 3, 2, 1, 1,
	3, 3, 1, 3, 2, 0, 2, 1, 3, 3,
	2, 1, 1, 1, 0, 1, 0, 1, 2, 2,
	0, 1, 1, 1, 1, 2, 3, 1, 2, 0,
	1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int{
	-1000, -91, -56, -55, -45, -36, -57, -31, -19, -27,
	-33, -58, -24, -25, -34, 77, 78, -39, -28, -59,
	83, 79, 81, 64, 80, 39, 63, 44, 45, -29,
	-38, -49, 38, -52, -30, -50, -51, -40, -32, 108,
	105, 87, 62, -44, 50, 52, 59, 69, 67, 46,
	-87, -1, 61, -53, -23, -22, -10, -21, -14, 48,
	-2, -26, 36, 40, 91, 101, 99, 102, 96, 82,
	42, 43, -92, -93, -7, 103, 89, 84, 51, 53,
	60, 70, 5, 5, -17, 6, 7, 8, 9, 10,
	104, 86, 111, 13, 14, 31, 32, 33, 34, 35,
	37, 27, 28, 26, 17, 18, 19, 20, 21, 29,
	30, 16, 15, 11, -8, 22, 24, 23, 25, -52,
	-24, -25, -34, -29, 62, -1, -8, -28, -31, -33,
	-24, -25, -34, 90, -45, -65, -60, -43, -28, -90,
	-89, -88, -43, 85, -66, 107, -61, -60, -89, -43,
	-86, 87, 76, -35, -27, -35, -41, -35, -41, -35,
	-92, -93, -16, 64, -81, -54, -55, -66, -63, 107,
	-61, -12, 95, -12, -5, -2, -4, 83, 64, 27,
	28, 26, 17, 18, 20, 21, 22, 23, 24, 25,
	19, 29, 30, 31, 32, 33, 34, 35, 37, 38,
	-26, -45, 89, 84, 89, -35, -35, -35, -35, -39,
	-68, -67, -43, -60, -67, -37, -42, -39, -36, -28,
	-31, -37, -42, -28, -62, -61, -60, 83, -5, 64,
	-28, -28, -28, -28, -28, -28, -28, -28, -28, -28,
	-28, -28, -28, -28, -28, -28, -28, -28, -28, -28,
	-28, -28, 90, 104, 86, -28, 5, -17, 104, -3,
	-94, 89, 106, -95, 90, 89, 88, -95, 90, 110,
	-43, -61, -3, 90, 90, -85, -76, 27, -85, -6,
	-7, 57, -6, -54, -20, -7, 76, -54, -92, -83,
	-82, 68, -18, 24, 49, -92, -62, -11, 95, -13,
	92, 93, 100, -15, 97, -73, 107, -74, -75, -80,
	-79, -69, -71, -77, -72, 83, -70, 26, 85, 89,
	90, 5, -9, -94, 90, -64, -63, -94, -62, -62,
	109, -43, -88, -43, -3, -89, -43, 88, -54, -75,
	83, 49, -54, 57, -54, 49, 49, -83, 49, -84,
	-48, 58, -83, -60, -81, 64, 109, -29, -34, -24,
	-25, -74, -7, 90, -78, -78, 90, 90, 5, 83,
	-43, -43, 106, 12, -9, -9, 27, 90, -46, -47,
	66, -48, 58, -47, 49, -54, 90, -6, 49, -7,
	94, 104, -3, -79, -80, -69, -71, 83, -70, -43,
	-28, 49, -27, -54, 49, -54, -62, -78, -6, -9,
	-54, -46,
}

var yyDef = [...]int{
	5, -2, 1, 234, 6, 12, 0, 0, 16, 17,
	0, 31, -2, -2, 0, 255, 256, 22, 23, 32,
	-2, 189, 190, -2, 192, 193, 194, 195, 196, -2,
	26, 84, 0, 0, 121, 122, 123, 124, 125, 0,
	103, 225, 132, 133, 0, 0, 0, 0, 234, 0,
	5, 0, 0, 34, 166, 167, 177, 0, 177, 0,
	27, 184, 0, 183, 172, 173, 170, 171, 180, 233,
	186, 187, 2, 235, 247, 243, 244, 0, 0, 0,
	0, 0, 0, 0, 0, 250, 251, 252, 253, 254,
	109, 0, 0, 72, 73, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 96, 97, 98, 99, 33,
	-2, -2, 0, 143, 132, 0, 0, 89, 0, 0,
	-2, -2, 0, 35, 236, 0, 240, 115, 102, 0,
	240, 227, 0, 0, 29, 236, 119, 112, 113, 115,
	134, 153, 153, 0, 24, 0, 5, 0, 5, 234,
	0, 235, 201, 44, 0, 3, 234, 28, 155, 109,
	30, 0, 0, 0, 213, 45, 46, 231, 232, 47,
	48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
	185, 7, 248, 0, 245, 8, 9, 10, 11, 13,
	15, 117, -2, 0, 14, 18, 68, 20, 21, -2,
	0, 19, 69, 105, 236, 110, 112, -2, 107, 127,
	-2, -2, 74, 75, 76, 77, 78, 79, 80, 81,
	82, -2, -2, -2, -2, -2, 90, 91, 92, 93,
	236, 100, 36, 109, 0, 101, 0, 0, 109, 126,
	0, 237, 128, 104, 242, 241, 129, 226, 242, 0,
	230, 236, 131, 0, 0, 0, 5, 0, 0, 5,
	144, 145, 5, 0, 25, 147, 148, 0, 0, 0,
	249, 0, 5, 0, 142, 4, 0, 168, 175, 176,
	174, 0, 169, 179, 181, 182, 213, 0, 208, 208,
	212, 215, 222, 205, 206, 214, 219, 0, 218, 246,
	0, 0, -2, 0, 111, 156, 108, 0, 236, 236,
	238, 116, 228, 229, 130, 114, 116, 158, 160, 0,
	214, 159, 249, 146, 249, 137, 138, 0, 140, 161,
	163, 5, 165, 0, 0, 0, 106, 143, 0, 197,
	198, 236, 204, 0, 210, 211, 0, 0, 0, 224,
	217, -2, 239, 0, -2, -2, 154, 0, 0, 149,
	0, 151, 5, 0, 139, 164, 0, 5, 141, 202,
	178, 109, 203, 207, 208, 216, 223, 0, 220, 221,
	94, 135, 0, 152, 136, 162, 236, 209, 5, 157,
	249, 150,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = true
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			setRoot(yylex, yyDollar[1].node_list)
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = yyDollar[1].node_list
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.body = &Body{Statements: yyDollar[1].node_list}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = yyDollar[1].node_list
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node_list = []Node{}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if root(yylex).CurrentState() == InClassBody {
				root(yylex).currentClass.AddStatement(yyDollar[1].node)
				yyVAL.node_list = []Node{}
			}
			yyVAL.node_list = []Node{yyDollar[1].node}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if root(yylex).CurrentState() == InClassBody {
				root(yylex).currentClass.AddStatement(yyDollar[3].node)
				yyVAL.node_list = []Node{}
			} else {
				yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[3].node)
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[3].node, True: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: &NotExpressionNode{Arg: yyDollar[3].node, lineNo: currentLineNo}, True: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: yyDollar[3].node, Body: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: &NotExpressionNode{Arg: yyDollar[3].node, lineNo: currentLineNo}, Body: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: yyDollar[1].node_list, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: yyDollar[1].node_list, Right: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).inPrivateMethods = true
			yyVAL.node = &NoopNode{}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
		{

			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			operation := &InfixExpressionNode{Left: yyDollar[1].node, Operator: strings.Trim(yyDollar[2].str, "="), Right: yyDollar[3].node, lineNo: currentLineNo}
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := &MethodCall{MethodName: yyDollar[1].str, Args: yyDollar[2].args, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", Args: yyDollar[2].args, lineNo: currentLineNo}
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			r := &ReturnNode{Val: yyDollar[2].args, lineNo: currentLineNo}
			root(yylex).AddReturn(r)
			yyVAL.node = r
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[2].node)
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = []Node{yyDollar[1].node}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[2].node)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAssignmentNode{
				Composite: yyDollar[1].node,
				Args:      yyDollar[3].args,
				lineNo:    currentLineNo,
			}
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAssignmentNode{
				Composite: yyDollar[1].node,
				Args:      yyDollar[3].args,
				lineNo:    currentLineNo,
			}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, lineNo: currentLineNo}
			yyVAL.node = call
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).PushClass(yyDollar[1].str, currentLineNo)
			yyVAL.str = yyDollar[1].str
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			operation := &InfixExpressionNode{Left: yyDollar[1].node, Operator: strings.Trim(yyDollar[2].str, "="), Right: yyDollar[3].node, lineNo: currentLineNo}
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Upper: yyDollar[3].node, Inclusive: true, lineNo: currentLineNo}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Upper: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 72:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Inclusive: true, lineNo: currentLineNo}
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, lineNo: currentLineNo}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &NotExpressionNode{Arg: yyDollar[2].node, lineNo: currentLineNo}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 94:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{
				Condition: yyDollar[1].node,
				True:      Statements{yyDollar[3].node},
				False: &Condition{
					True: Statements{yyDollar[6].node},
				},
				lineNo: currentLineNo,
			}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 103:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = nil
		}
	case 104:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.args = yyDollar[1].args
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = yyDollar[2].args
		}
	case 107:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = ArgsNode{}
		}
	case 109:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = ArgsNode{}
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = yyDollar[1].args
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			for _, kv := range yyDollar[1].kvs {
				yyVAL.args = append(yyVAL.args, kv)
			}
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			for _, kv := range yyDollar[3].kvs {
				yyDollar[1].args = append(yyDollar[1].args, kv)
			}
			yyVAL.args = yyDollar[1].args
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = ArgsNode{yyDollar[1].node}
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].node)
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = []Node{yyDollar[1].node}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].node)
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ScopeAccessNode{Receiver: yyDollar[1].node, Constant: yyDollar[3].str, lineNo: currentLineNo}
		}
	case 128:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ArrayNode{Args: yyDollar[2].args, lineNo: currentLineNo}
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &HashNode{Pairs: yyDollar[2].kvs, lineNo: currentLineNo}
		}
	case 130:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			// this is naive, as in theory the source could have non-block locals called "blk".
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", Args: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", lineNo: currentLineNo}
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", lineNo: currentLineNo}
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := yyDollar[1].node.(*MethodCall)
			call.SetBlock(yyDollar[2].blk)
			if yylex.(*Lexer).gauntlet && call.MethodName == "gauntlet" {
				lines := strings.Split(yylex.(*Lexer).lastParsedToken.RawBlock, "\n")
				call.RawBlock = strings.Join(lines[1:len(lines)-1], "\n")
				yylex.(*Lexer).gauntlet = false
			}
			yyVAL.node = call
		}
	case 135:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[2].node, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 136:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: &NotExpressionNode{Arg: yyDollar[2].node, lineNo: currentLineNo}, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 137:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: yyDollar[2].node, Body: yyDollar[3].node_list, lineNo: yyDollar[2].node.LineNo()}
		}
	case 138:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: &NotExpressionNode{Arg: yyDollar[2].node, lineNo: yyDollar[2].node.LineNo()}, Body: yyDollar[3].node_list, lineNo: yyDollar[2].node.LineNo()}
		}
	case 139:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &CaseNode{Value: yyDollar[2].node, Whens: yyDollar[4].whens, lineNo: currentLineNo}
		}
	case 140:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &CaseNode{Whens: yyDollar[3].whens, lineNo: currentLineNo}
		}
	case 141:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			root(yylex).currentClass.Superclass = yyDollar[3].str
			yyVAL.node = root(yylex).PopClass()
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[1].meth.Body = yyDollar[2].body
			root(yylex).AddMethod(yyDollar[1].meth)
			root(yylex).PopState()
			root(yylex).PopScope()
			yyVAL.node = yyDollar[1].meth
		}
	case 146:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 150:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[2].node, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 152:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &Condition{True: yyDollar[2].node_list, lineNo: currentLineNo}
		}
	case 153:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 155:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := &MethodCall{MethodName: yyDollar[1].str, Args: yyDollar[2].args, lineNo: currentLineNo}
			if root(yylex).currentClass != nil {
				root(yylex).currentClass.MethodSet.AddCall(call)
			} else {
				root(yylex).AddCall(call)
			}
			yyVAL.node = call
		}
	case 156:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 157:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAccessNode{Composite: yyDollar[1].node, Args: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.blk = yyDollar[2].blk
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.blk = yyDollar[2].blk
		}
	case 160:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			blk := &Block{Body: &Body{Statements: yyDollar[2].node_list}, ParamList: NewParamList()}
			for _, p := range yyDollar[1].params {
				blk.AddParam(p)
			}
			yyVAL.blk = blk
		}
	case 161:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.whens = append([]*WhenNode{yyDollar[1].when}, yyDollar[2].whens...)
		}
	case 162:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.when = &WhenNode{Conditions: yyDollar[2].args, Statements: yyDollar[4].node_list, lineNo: currentLineNo}
		}
	case 163:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.whens = []*WhenNode{}
		}
	case 164:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.whens = []*WhenNode{&WhenNode{Statements: yyDollar[2].node_list, lineNo: currentLineNo}}
		}
	case 168:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = root(yylex).PopString()
		}
	case 169:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &StringNode{BodySegments: []string{yyDollar[2].str}, Kind: getStringKind(yyDollar[1].str), lineNo: currentLineNo}
		}
	case 172:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).PushState(InString)
			root(yylex).PushString(getStringKind(yyDollar[1].str))
			yyVAL.str = ""
		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).PushState(InString)
			root(yylex).PushString(getStringKind(yyDollar[1].str))
			yyVAL.str = ""
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).PopState()
			yyVAL.str = ""
		}
	case 175:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			curr := root(yylex).CurrentString()
			curr.BodySegments = append(curr.BodySegments, yyDollar[2].str)
			yyVAL.str = ""
		}
	case 176:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 177:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 178:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			curr := root(yylex).CurrentString()
			curr.Interps[len(curr.BodySegments)] = append(curr.Interps[len(curr.BodySegments)], yyDollar[2].node)
			yyVAL.str = ""
		}
	case 179:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			regexp := root(yylex).PopString()
			yyVAL.node = regexp
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).PushState(InString)
			root(yylex).PushString(Regexp)
			yyVAL.str = ""
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).PopState()
			yyVAL.str = ""
		}
	case 182:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			method := NewMethod(yyDollar[2].str, root(yylex))
			method.Private = root(yylex).inPrivateMethods
			method.lineNo = currentLineNo

			for _, p := range yyDollar[3].params {
				if err := method.AddParam(p); err != nil {
					root(yylex).AddError(err)
				}
			}

			root(yylex).PushState(InMethodDefinition)
			root(yylex).PushScope(method.Locals)
			yyVAL.meth = method
		}
	case 183:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &SymbolNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 185:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			var negative Node
			switch x := yyDollar[2].node.(type) {
			case *IntNode:
				x.Val = yyDollar[1].str + x.Val
				negative = x
			case *Float64Node:
				x.Val = yyDollar[1].str + x.Val
				negative = x
			}
			yyVAL.node = negative
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &IntNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &Float64Node{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &IdentNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			ivar := &IVarNode{Val: yyDollar[1].str, Class: root(yylex).currentClass, lineNo: currentLineNo}
			yyVAL.node = ivar
			cls := root(yylex).currentClass
			if cls != nil {
				cls.AddIVar(ivar.NormalizedVal(), &IVar{Name: ivar.NormalizedVal()})
			}
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &GVarNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ConstantNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &CVarNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &NilNode{lineNo: currentLineNo}
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &SelfNode{lineNo: currentLineNo}
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BooleanNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BooleanNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 201:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 202:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 203:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 204:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = yyDollar[1].params
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 207:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 208:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 209:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.params = append(append(yyDollar[1].params, yyDollar[3].params...), yyDollar[4].params...)
		}
	case 210:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[2].params...)
		}
	case 211:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[2].params...)
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = yyDollar[1].params
		}
	case 213:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 214:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[1].str, Kind: Positional}
		}
	case 215:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 216:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 217:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.param = &Param{Name: strings.Trim(yyDollar[1].str, ":"), Default: yyDollar[2].node, Kind: Keyword}
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.param = &Param{Name: strings.Trim(yyDollar[1].str, ":"), Kind: Keyword}
		}
	case 219:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 220:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 221:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[1].str, Default: yyDollar[3].node, Kind: Named}
		}
	case 222:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 223:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 224:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[2].str, Kind: ExplicitBlock}
		}
	case 225:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.kvs = []*KeyValuePair{}
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.kvs = []*KeyValuePair{yyDollar[1].kv}
		}
	case 228:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.kvs = append(yyDollar[1].kvs, yyDollar[3].kv)
		}
	case 229:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.kv = &KeyValuePair{Key: yyDollar[1].node, Value: yyDollar[3].node}
		}
	case 230:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.kv = &KeyValuePair{Label: strings.TrimRight(yyDollar[1].str, ":"), Value: yyDollar[2].node}
		}
	case 238:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 239:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 245:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			root(yylex).AddComment(Comment{Text: yyDollar[1].str, LineNo: currentLineNo})
			yyVAL.str = yyDollar[2].str
		}
	case 246:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			root(yylex).AddComment(Comment{Text: yyDollar[2].str, LineNo: currentLineNo})
			yyVAL.str = yyDollar[3].str
		}
	case 249:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	}
	goto yystack /* stack new state and value */
}
