// Code generated by goyacc -l -o ruby.go ruby.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import "strings"

func setRoot(yylex yyLexer, nodes []Node) {
	p := yylex.(*Lexer).Root
	for _, n := range nodes {
		p.AddStatement(n)
	}
}

func root(yylex yyLexer) *Root {
	return yylex.(*Lexer).Root
}

type yySymType struct {
	yys       int
	args      ArgsNode
	blk       *Block
	body      *Body
	kv        *KeyValuePair
	kvs       []*KeyValuePair
	meth      *Method
	node      Node
	node_list Statements
	param     *Param
	params    []*Param
	root      *Root
	regexp    string
	when      *WhenNode
	whens     []*WhenNode
	str       string
}

const LOWEST = 57346
const ASSIGN = 57347
const MODASSIGN = 57348
const MULASSIGN = 57349
const ADDASSIGN = 57350
const SUBASSIGN = 57351
const DIVASSIGN = 57352
const LSHIFTASSIGN = 57353
const RSHIFTASSIGN = 57354
const QMARK = 57355
const COLON = 57356
const DOT2 = 57357
const DOT3 = 57358
const LOGICALOR = 57359
const LOGICALAND = 57360
const SPACESHIP = 57361
const EQ = 57362
const NEQ = 57363
const MATCH = 57364
const NOTMATCH = 57365
const GT = 57366
const GTE = 57367
const LT = 57368
const LTE = 57369
const AND = 57370
const PIPE = 57371
const CARET = 57372
const LSHIFT = 57373
const RSHIFT = 57374
const PLUS = 57375
const MINUS = 57376
const ASTERISK = 57377
const SLASH = 57378
const MODULO = 57379
const UNARY_NUM = 57380
const POW = 57381
const BANG = 57382
const NIL = 57383
const SYMBOL = 57384
const STRING = 57385
const INT = 57386
const FLOAT = 57387
const TRUE = 57388
const FALSE = 57389
const CLASS = 57390
const MODULE = 57391
const DEF = 57392
const END = 57393
const IF = 57394
const IF_MOD = 57395
const UNLESS = 57396
const UNLESS_MOD = 57397
const BEGIN = 57398
const RESCUE = 57399
const RESCUE_MOD = 57400
const THEN = 57401
const ELSE = 57402
const WHILE = 57403
const WHILE_MOD = 57404
const RETURN = 57405
const YIELD = 57406
const SELF = 57407
const CONSTANT = 57408
const ENSURE = 57409
const ELSIF = 57410
const CASE = 57411
const WHEN = 57412
const UNTIL = 57413
const UNTIL_MOD = 57414
const FOR = 57415
const BREAK = 57416
const NEXT = 57417
const SUPER = 57418
const ALIAS = 57419
const DO = 57420
const DO_COND = 57421
const DO_BLOCK = 57422
const PRIVATE = 57423
const PROTECTED = 57424
const IVAR = 57425
const CVAR = 57426
const GVAR = 57427
const METHODIDENT = 57428
const IDENT = 57429
const COMMENT = 57430
const LABEL = 57431
const ANDDOT = 57432
const DOT = 57433
const LBRACE = 57434
const LBRACEBLOCK = 57435
const RBRACE = 57436
const NEWLINE = 57437
const COMMA = 57438
const STRINGBEG = 57439
const STRINGEND = 57440
const INTERPBEG = 57441
const INTERPEND = 57442
const STRINGBODY = 57443
const REGEXBEG = 57444
const REGEXEND = 57445
const REGEXPOPT = 57446
const RAWSTRINGBEG = 57447
const RAWSTRINGEND = 57448
const WORDSBEG = 57449
const RAWWORDSBEG = 57450
const XSTRINGBEG = 57451
const RAWXSTRINGBEG = 57452
const SEMICOLON = 57453
const LBRACKET = 57454
const LBRACKETSTART = 57455
const RBRACKET = 57456
const LPAREN = 57457
const LPARENSTART = 57458
const RPAREN = 57459
const HASHROCKET = 57460
const SCOPE = 57461

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LOWEST",
	"ASSIGN",
	"MODASSIGN",
	"MULASSIGN",
	"ADDASSIGN",
	"SUBASSIGN",
	"DIVASSIGN",
	"LSHIFTASSIGN",
	"RSHIFTASSIGN",
	"QMARK",
	"COLON",
	"DOT2",
	"DOT3",
	"LOGICALOR",
	"LOGICALAND",
	"SPACESHIP",
	"EQ",
	"NEQ",
	"MATCH",
	"NOTMATCH",
	"GT",
	"GTE",
	"LT",
	"LTE",
	"AND",
	"PIPE",
	"CARET",
	"LSHIFT",
	"RSHIFT",
	"PLUS",
	"MINUS",
	"ASTERISK",
	"SLASH",
	"MODULO",
	"UNARY_NUM",
	"POW",
	"BANG",
	"NIL",
	"SYMBOL",
	"STRING",
	"INT",
	"FLOAT",
	"TRUE",
	"FALSE",
	"CLASS",
	"MODULE",
	"DEF",
	"END",
	"IF",
	"IF_MOD",
	"UNLESS",
	"UNLESS_MOD",
	"BEGIN",
	"RESCUE",
	"RESCUE_MOD",
	"THEN",
	"ELSE",
	"WHILE",
	"WHILE_MOD",
	"RETURN",
	"YIELD",
	"SELF",
	"CONSTANT",
	"ENSURE",
	"ELSIF",
	"CASE",
	"WHEN",
	"UNTIL",
	"UNTIL_MOD",
	"FOR",
	"BREAK",
	"NEXT",
	"SUPER",
	"ALIAS",
	"DO",
	"DO_COND",
	"DO_BLOCK",
	"PRIVATE",
	"PROTECTED",
	"IVAR",
	"CVAR",
	"GVAR",
	"METHODIDENT",
	"IDENT",
	"COMMENT",
	"LABEL",
	"ANDDOT",
	"DOT",
	"LBRACE",
	"LBRACEBLOCK",
	"RBRACE",
	"NEWLINE",
	"COMMA",
	"STRINGBEG",
	"STRINGEND",
	"INTERPBEG",
	"INTERPEND",
	"STRINGBODY",
	"REGEXBEG",
	"REGEXEND",
	"REGEXPOPT",
	"RAWSTRINGBEG",
	"RAWSTRINGEND",
	"WORDSBEG",
	"RAWWORDSBEG",
	"XSTRINGBEG",
	"RAWXSTRINGBEG",
	"SEMICOLON",
	"LBRACKET",
	"LBRACKETSTART",
	"RBRACKET",
	"LPAREN",
	"LPARENSTART",
	"RPAREN",
	"HASHROCKET",
	"SCOPE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 13,
	5, 51,
	6, 223,
	7, 223,
	8, 223,
	9, 223,
	10, 223,
	11, 223,
	12, 223,
	96, 47,
	-2, 221,
	-1, 14,
	5, 52,
	6, 224,
	7, 224,
	8, 224,
	9, 224,
	10, 224,
	11, 224,
	12, 224,
	96, 48,
	-2, 222,
	-1, 22,
	38, 255,
	40, 255,
	41, 255,
	42, 255,
	44, 255,
	45, 255,
	46, 255,
	47, 255,
	48, 255,
	49, 255,
	50, 255,
	52, 255,
	54, 255,
	61, 255,
	64, 255,
	65, 255,
	66, 255,
	69, 255,
	71, 255,
	74, 255,
	75, 255,
	76, 255,
	83, 255,
	84, 255,
	85, 255,
	86, 255,
	87, 255,
	89, 255,
	92, 255,
	97, 255,
	102, 255,
	105, 255,
	107, 255,
	108, 255,
	109, 255,
	110, 255,
	113, 255,
	115, 255,
	116, 255,
	-2, 212,
	-1, 25,
	38, 256,
	40, 256,
	41, 256,
	42, 256,
	44, 256,
	45, 256,
	46, 256,
	47, 256,
	48, 256,
	49, 256,
	50, 256,
	52, 256,
	54, 256,
	61, 256,
	64, 256,
	65, 256,
	66, 256,
	69, 256,
	71, 256,
	74, 256,
	75, 256,
	76, 256,
	83, 256,
	84, 256,
	85, 256,
	86, 256,
	87, 256,
	89, 256,
	92, 256,
	97, 256,
	102, 256,
	105, 256,
	107, 256,
	108, 256,
	109, 256,
	110, 256,
	113, 256,
	115, 256,
	116, 256,
	-2, 215,
	-1, 31,
	90, 160,
	91, 160,
	112, 160,
	119, 160,
	-2, 108,
	-1, 43,
	38, 132,
	40, 132,
	41, 132,
	42, 132,
	44, 132,
	45, 132,
	46, 132,
	47, 132,
	48, 132,
	49, 132,
	50, 132,
	52, 132,
	54, 132,
	61, 132,
	64, 132,
	65, 132,
	66, 132,
	69, 132,
	71, 132,
	74, 132,
	75, 132,
	76, 132,
	83, 132,
	84, 132,
	85, 132,
	86, 132,
	87, 132,
	89, 132,
	92, 132,
	97, 132,
	102, 132,
	105, 132,
	107, 132,
	108, 132,
	109, 132,
	110, 132,
	113, 132,
	116, 132,
	-2, 146,
	-1, 56,
	38, 132,
	40, 132,
	41, 132,
	42, 132,
	44, 132,
	45, 132,
	46, 132,
	47, 132,
	48, 132,
	49, 132,
	50, 132,
	52, 132,
	54, 132,
	61, 132,
	64, 132,
	65, 132,
	66, 132,
	69, 132,
	71, 132,
	74, 132,
	75, 132,
	76, 132,
	83, 132,
	84, 132,
	85, 132,
	86, 132,
	87, 132,
	89, 132,
	92, 132,
	97, 132,
	102, 132,
	105, 132,
	107, 132,
	108, 132,
	109, 132,
	110, 132,
	113, 132,
	116, 132,
	-2, 178,
	-1, 105,
	5, 38,
	-2, 40,
	-1, 118,
	5, 51,
	6, 223,
	7, 223,
	8, 223,
	9, 223,
	10, 223,
	11, 223,
	12, 223,
	-2, 221,
	-1, 119,
	5, 52,
	6, 224,
	7, 224,
	8, 224,
	9, 224,
	10, 224,
	11, 224,
	12, 224,
	-2, 222,
	-1, 148,
	90, 221,
	91, 221,
	112, 221,
	119, 221,
	-2, 47,
	-1, 149,
	90, 222,
	91, 222,
	112, 222,
	119, 222,
	-2, 48,
	-1, 241,
	96, 128,
	-2, 131,
	-1, 248,
	96, 115,
	-2, 118,
	-1, 258,
	38, 132,
	40, 132,
	41, 132,
	42, 132,
	44, 132,
	45, 132,
	46, 132,
	47, 132,
	48, 132,
	49, 132,
	50, 132,
	52, 132,
	54, 132,
	61, 132,
	64, 132,
	65, 132,
	66, 132,
	69, 132,
	71, 132,
	74, 132,
	75, 132,
	76, 132,
	83, 132,
	84, 132,
	85, 132,
	86, 132,
	87, 132,
	89, 132,
	92, 132,
	97, 132,
	102, 132,
	105, 132,
	107, 132,
	108, 132,
	109, 132,
	110, 132,
	113, 132,
	116, 132,
	-2, 58,
	-1, 259,
	5, 54,
	96, 50,
	-2, 255,
	-1, 269,
	15, 0,
	16, 0,
	-2, 83,
	-1, 270,
	15, 0,
	16, 0,
	-2, 84,
	-1, 280,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 96,
	-1, 281,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 98,
	-1, 282,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 99,
	-1, 283,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 100,
	-1, 284,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 101,
	-1, 333,
	1, 120,
	51, 120,
	53, 120,
	55, 120,
	59, 120,
	60, 120,
	62, 120,
	68, 120,
	70, 120,
	72, 120,
	79, 120,
	88, 120,
	91, 120,
	94, 120,
	95, 120,
	111, 120,
	117, 120,
	-2, 132,
	-1, 359,
	5, 39,
	-2, 41,
	-1, 363,
	5, 53,
	96, 49,
	-2, 179,
	-1, 365,
	5, 54,
	-2, 255,
	-1, 369,
	5, 50,
	95, 50,
	96, 50,
	117, 50,
	-2, 255,
	-1, 418,
	96, 129,
	-2, 134,
	-1, 419,
	5, 53,
	-2, 179,
	-1, 421,
	5, 49,
	95, 49,
	96, 49,
	117, 49,
	-2, 179,
}

const yyPrivate = 57344

const yyLast = 1782

var yyAct = [...]int{
	20, 424, 411, 346, 314, 18, 425, 31, 166, 347,
	353, 348, 298, 361, 349, 344, 261, 5, 83, 84,
	113, 427, 197, 300, 345, 112, 254, 307, 358, 151,
	192, 170, 87, 374, 187, 82, 95, 339, 201, 436,
	111, 110, 162, 162, 103, 111, 110, 302, 306, 111,
	110, 169, 294, 11, 422, 107, 9, 262, 162, 188,
	4, 245, 438, 302, 301, 165, 105, 268, 183, 109,
	322, 292, 413, 104, 109, 111, 110, 338, 109, 335,
	332, 341, 68, 414, 244, 182, 337, 338, 410, 335,
	364, 88, 115, 10, 162, 248, 252, 108, 86, 238,
	246, 246, 176, 176, 109, 10, 176, 190, 193, 162,
	356, 331, 247, 247, 85, 195, 232, 113, 291, 158,
	263, 423, 269, 270, 271, 272, 273, 274, 275, 276,
	277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
	287, 288, 289, 290, 230, 10, 176, 176, 176, 176,
	204, 257, 266, 255, 88, 163, 15, 251, 297, 240,
	105, 231, 160, 191, 379, 304, 199, 104, 15, 162,
	174, 162, 162, 267, 354, 117, 10, 150, 196, 355,
	250, 104, 317, 354, 233, 173, 299, 10, 10, 305,
	258, 253, 373, 162, 354, 315, 416, 315, 156, 10,
	183, 117, 117, 324, 428, 117, 293, 397, 15, 330,
	114, 7, 426, 10, 242, 242, 232, 321, 69, 303,
	194, 327, 89, 7, 90, 329, 312, 313, 309, 311,
	264, 91, 428, 352, 185, 355, 176, 382, 318, 15,
	320, 92, 444, 184, 355, 117, 117, 117, 117, 117,
	117, 117, 451, 352, 243, 355, 296, 200, 198, 119,
	14, 343, 15, 7, 255, 393, 252, 252, 326, 162,
	260, 10, 14, 10, 363, 324, 15, 153, 55, 10,
	448, 149, 333, 207, 434, 366, 430, 398, 299, 229,
	55, 196, 196, 162, 7, 186, 256, 55, 118, 13,
	161, 167, 162, 79, 206, 249, 249, 162, 162, 368,
	360, 13, 14, 390, 388, 376, 367, 7, 194, 384,
	148, 372, 202, 55, 55, 162, 380, 55, 251, 370,
	55, 7, 162, 162, 15, 117, 15, 328, 203, 386,
	128, 376, 15, 14, 420, 392, 404, 403, 415, 412,
	258, 13, 241, 161, 400, 371, 162, 162, 252, 408,
	396, 55, 310, 246, 409, 162, 14, 55, 55, 55,
	55, 55, 55, 55, 381, 247, 204, 383, 142, 419,
	14, 421, 13, 178, 55, 402, 204, 400, 10, 7,
	429, 7, 389, 299, 394, 299, 357, 7, 55, 265,
	433, 80, 81, 94, 35, 13, 93, 10, 189, 3,
	10, 171, 179, 157, 441, 315, 162, 435, 10, 13,
	440, 447, 442, 440, 362, 445, 147, 308, 443, 1,
	164, 52, 180, 162, 155, 442, 172, 391, 14, 162,
	14, 323, 175, 350, 454, 395, 14, 295, 342, 359,
	10, 15, 351, 431, 455, 453, 55, 55, 55, 458,
	239, 437, 316, 89, 55, 90, 456, 316, 159, 315,
	15, 21, 91, 15, 125, 126, 127, 13, 128, 13,
	299, 15, 92, 449, 6, 13, 10, 2, 450, 177,
	59, 88, 181, 452, 405, 387, 88, 362, 86, 432,
	38, 378, 37, 86, 88, 34, 7, 143, 145, 144,
	146, 86, 44, 117, 85, 457, 58, 33, 39, 85,
	204, 10, 399, 32, 40, 7, 10, 85, 7, 36,
	60, 61, 234, 235, 236, 237, 7, 129, 130, 137,
	138, 123, 124, 125, 126, 127, 51, 128, 10, 15,
	123, 124, 125, 126, 127, 14, 128, 50, 63, 385,
	375, 8, 325, 340, 64, 167, 377, 336, 249, 334,
	62, 205, 0, 55, 14, 0, 0, 14, 0, 0,
	0, 0, 117, 161, 15, 14, 0, 0, 0, 15,
	401, 167, 55, 0, 13, 55, 0, 0, 407, 0,
	439, 0, 0, 55, 7, 0, 0, 0, 0, 0,
	0, 15, 0, 13, 417, 418, 13, 0, 0, 0,
	0, 0, 319, 401, 13, 131, 129, 130, 137, 138,
	123, 124, 125, 126, 127, 55, 128, 406, 0, 7,
	0, 0, 0, 0, 7, 0, 137, 138, 123, 124,
	125, 126, 127, 14, 128, 96, 97, 98, 99, 100,
	101, 102, 0, 0, 0, 0, 7, 0, 0, 0,
	0, 55, 0, 0, 446, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 14, 0,
	0, 375, 13, 14, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 55, 0, 55, 0, 0, 0,
	0, 55, 0, 0, 70, 14, 19, 27, 71, 0,
	80, 81, 29, 30, 65, 66, 67, 13, 45, 0,
	46, 0, 13, 55, 0, 0, 0, 47, 0, 57,
	43, 28, 25, 0, 0, 49, 0, 48, 0, 0,
	53, 54, 56, 0, 13, 0, 0, 16, 17, 23,
	26, 24, 79, 22, 88, 0, 0, 0, 42, 0,
	0, 231, 0, 72, 0, 0, 0, 0, 78, 0,
	0, 75, 0, 73, 76, 74, 77, 0, 0, 41,
	0, 70, 12, 19, 27, 71, 0, 80, 81, 29,
	30, 65, 66, 67, 0, 45, 0, 46, 0, 0,
	0, 0, 0, 0, 47, 0, 57, 43, 28, 25,
	0, 0, 49, 0, 48, 0, 0, 53, 54, 56,
	0, 0, 0, 0, 0, 0, 23, 26, 24, 79,
	22, 88, 0, 0, 0, 42, 0, 0, 86, 0,
	72, 0, 0, 0, 0, 78, 0, 0, 75, 0,
	73, 76, 74, 77, 85, 0, 41, 0, 70, 120,
	19, 27, 71, 0, 80, 81, 29, 30, 65, 66,
	67, 0, 45, 0, 46, 0, 0, 0, 0, 0,
	0, 47, 0, 57, 43, 28, 25, 0, 0, 49,
	0, 48, 0, 0, 53, 54, 56, 0, 0, 0,
	0, 16, 17, 23, 26, 24, 79, 22, 0, 0,
	0, 0, 42, 0, 0, 0, 0, 72, 0, 0,
	0, 0, 78, 0, 0, 75, 0, 73, 76, 74,
	77, 0, 0, 41, 0, 70, 12, 19, 27, 71,
	0, 80, 81, 29, 30, 65, 66, 67, 0, 45,
	0, 46, 0, 0, 0, 0, 0, 0, 47, 0,
	57, 43, 28, 25, 0, 0, 49, 0, 48, 0,
	0, 53, 54, 56, 0, 0, 0, 0, 16, 17,
	23, 26, 24, 79, 22, 0, 0, 0, 0, 42,
	0, 0, 0, 0, 72, 0, 0, 0, 0, 78,
	0, 0, 75, 0, 73, 76, 74, 77, 0, 0,
	41, 0, 70, 106, 116, 27, 71, 0, 80, 81,
	29, 30, 65, 66, 67, 0, 45, 0, 46, 0,
	0, 0, 0, 0, 0, 47, 0, 0, 152, 28,
	25, 0, 0, 49, 0, 48, 0, 0, 53, 54,
	154, 0, 0, 0, 0, 0, 0, 23, 26, 24,
	79, 22, 0, 168, 0, 0, 42, 0, 0, 255,
	0, 72, 0, 0, 0, 0, 78, 0, 0, 75,
	0, 73, 76, 74, 77, 0, 0, 41, 0, 70,
	120, 116, 27, 71, 0, 80, 81, 29, 30, 65,
	66, 67, 0, 45, 0, 46, 0, 0, 0, 0,
	0, 0, 47, 0, 0, 152, 28, 25, 0, 0,
	49, 0, 48, 0, 0, 53, 54, 154, 0, 0,
	0, 0, 0, 0, 23, 26, 24, 79, 22, 0,
	168, 0, 0, 42, 0, 0, 0, 0, 72, 0,
	0, 0, 0, 78, 0, 0, 75, 0, 73, 76,
	74, 77, 0, 0, 41, 0, 70, 120, 19, 27,
	71, 0, 80, 81, 29, 30, 65, 66, 67, 0,
	45, 0, 46, 0, 0, 0, 0, 0, 0, 47,
	0, 57, 43, 28, 25, 0, 0, 49, 0, 48,
	0, 0, 53, 54, 56, 0, 0, 0, 0, 0,
	0, 23, 26, 24, 79, 22, 0, 0, 0, 0,
	42, 0, 0, 0, 0, 72, 0, 0, 0, 0,
	78, 0, 0, 75, 0, 73, 76, 74, 77, 0,
	0, 41, 0, 70, 120, 116, 27, 71, 0, 80,
	81, 29, 30, 65, 66, 67, 0, 45, 0, 46,
	0, 0, 0, 0, 0, 0, 47, 0, 57, 43,
	28, 25, 0, 0, 49, 0, 48, 0, 0, 53,
	54, 56, 0, 0, 0, 0, 0, 0, 23, 26,
	24, 79, 22, 0, 0, 0, 0, 42, 0, 0,
	0, 0, 72, 0, 0, 0, 0, 78, 0, 0,
	75, 0, 73, 76, 74, 77, 0, 0, 41, 0,
	70, 120, 116, 27, 71, 0, 80, 81, 29, 30,
	65, 66, 67, 0, 45, 0, 46, 0, 0, 0,
	0, 0, 0, 47, 0, 0, 152, 28, 25, 0,
	0, 49, 0, 48, 0, 0, 53, 54, 154, 0,
	0, 0, 0, 0, 0, 23, 26, 24, 79, 22,
	0, 0, 0, 0, 42, 0, 0, 0, 0, 72,
	0, 0, 0, 0, 78, 0, 0, 75, 0, 73,
	76, 74, 77, 70, 0, 41, 27, 71, 120, 80,
	81, 29, 30, 65, 66, 67, 0, 45, 0, 46,
	0, 0, 0, 0, 0, 0, 47, 0, 0, 152,
	28, 25, 0, 0, 49, 0, 48, 0, 0, 53,
	54, 154, 0, 0, 0, 0, 0, 0, 23, 26,
	24, 79, 22, 0, 0, 0, 0, 42, 0, 0,
	0, 0, 72, 0, 0, 0, 0, 78, 0, 0,
	75, 0, 73, 76, 74, 77, 0, 0, 41, 0,
	141, 120, 121, 122, 140, 139, 132, 133, 134, 135,
	136, 143, 145, 144, 146, 131, 129, 130, 137, 138,
	123, 124, 125, 126, 127, 0, 128, 211, 212, 219,
	213, 214, 215, 216, 217, 218, 210, 208, 209, 220,
	221, 222, 223, 224, 225, 226, 0, 227, 228, 211,
	212, 219, 213, 214, 215, 216, 217, 218, 210, 208,
	209, 220, 221, 222, 223, 224, 225, 226, 0, 227,
	228, 0, 0, 0, 207, 0, 0, 0, 0, 0,
	0, 0, 255, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 79, 206, 207, 143, 145, 144,
	146, 131, 129, 130, 137, 138, 123, 124, 125, 126,
	127, 0, 128, 0, 0, 0, 79, 365, 211, 212,
	219, 213, 214, 215, 216, 217, 218, 210, 208, 209,
	220, 221, 222, 223, 224, 225, 226, 0, 227, 228,
	211, 212, 219, 213, 214, 215, 216, 217, 218, 210,
	208, 209, 220, 221, 222, 223, 224, 225, 226, 0,
	227, 228, 0, 0, 0, 207, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 79, 369, 207, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 79, 259, 141,
	0, 121, 122, 140, 139, 132, 133, 134, 135, 136,
	143, 145, 144, 146, 131, 129, 130, 137, 138, 123,
	124, 125, 126, 127, 0, 128, 140, 139, 132, 133,
	134, 135, 136, 143, 145, 144, 146, 131, 129, 130,
	137, 138, 123, 124, 125, 126, 127, 0, 128, 139,
	132, 133, 134, 135, 136, 143, 145, 144, 146, 131,
	129, 130, 137, 138, 123, 124, 125, 126, 127, 0,
	128, 132, 133, 134, 135, 136, 143, 145, 144, 146,
	131, 129, 130, 137, 138, 123, 124, 125, 126, 127,
	0, 128,
}

var yyPact = [...]int{
	830, -1000, -1000, 3, 410, -1000, 401, 398, -1000, -1000,
	649, -1000, 907, -1000, -1000, -15, -1000, -1000, -1000, 1215,
	1676, 1365, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 118, -1000, 483, 23, -1000, -1000, -1000, -1000,
	-1000, 1292, 1061, -84, 92, 1138, 1138, -1000, -1000, 753,
	168, 168, 830, -1000, -1000, -85, -85, 1061, 75, -1000,
	-1000, -1000, -1000, -63, -1000, -1000, -1000, 1488, -1000, -1000,
	357, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 676, -1000, -1000, -1000, 96, -1000, 1138,
	1138, 1138, 1138, 1215, 1215, 1215, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 58, 169, -1000, 907, 1601, 1061, 164,
	-1000, -1000, -1000, -1000, 394, 649, 1292, -45, -1000, -1000,
	830, 1292, 1292, 1292, 1292, 1292, 1292, 1292, 1292, 1292,
	1292, 1292, 1292, 1292, 1292, 1292, 1292, 1292, 1292, 1292,
	1292, 1292, 1292, -1000, -1000, -1000, -1000, 22, -1000, -1000,
	-41, -1000, -84, -85, -85, -1000, 227, 1292, -1000, 58,
	-32, -1000, 1676, -45, 71, -48, -1000, -91, 1292, -1000,
	984, 1061, -1000, 227, 227, 408, -1000, 408, 830, 1138,
	830, 3, 133, 66, 242, -1000, 830, 286, -1000, 3,
	-1000, -1000, 1061, -1000, -1000, -1000, 15, -16, -91, 217,
	-12, -69, -22, 146, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	410, -1000, 96, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 14, -1000, -1000, -1000, -1000, -1000, 1676, 391,
	-1000, -1000, 1676, -1000, -89, -1000, -1000, 58, -1000, -1000,
	-85, 58, -1000, -6, -1000, 1292, 1292, 1510, 1061, 1699,
	1699, 439, 439, 301, 301, 301, 301, 615, 615, 508,
	1553, 1553, 1553, 1553, 1553, 517, 517, 1742, 1721, 1467,
	597, -1000, 1061, 1579, 278, 830, 105, 597, -1000, -81,
	-1000, 1292, -1000, 1510, -1000, -1000, 1061, 1292, -1000, 58,
	-1000, -1000, 70, 275, 830, 178, -1000, 830, 268, 416,
	263, 133, 262, 205, 1292, 830, 141, 236, -1000, -1000,
	58, 1061, 1061, -85, -1000, -1000, -1000, -1000, 1365, -1000,
	-1000, -1000, -1000, 166, 3, -8, -24, -1000, -1000, -1000,
	-13, -1000, 343, -1000, 109, 1292, 1292, 1215, -1000, -1000,
	-1000, -1000, -1000, -1000, 1061, -1000, 58, 330, 58, -1000,
	-1000, -1000, 25, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 144, -1000, 172, -1000, -1000, -1000, -1000, -1000, 235,
	-1000, -1000, -1000, 830, -1000, 403, 233, 3, -1000, -1000,
	-16, -91, -1000, -1000, -61, -50, -1000, -1000, 58, -1000,
	166, -1000, -1000, 155, 90, 1292, -1000, -1000, -1000, -1000,
	1292, -1000, -1000, 105, 229, -1000, 1138, -1000, 830, 201,
	-1000, -1000, 1292, 830, -1000, -1000, -1000, 1488, 1061, -1000,
	-1000, -24, -1000, -1000, 343, -1000, -1000, 1676, -1000, 408,
	-1000, -1000, -1000, 58, -1000, 830, -1000, 144, -1000,
}

var yyPgo = [...]int{
	0, 277, 82, 191, 571, 270, 4, 19, 378, 12,
	570, 569, 257, 567, 564, 563, 243, 36, 562, 561,
	559, 558, 557, 546, 32, 55, 531, 530, 298, 259,
	218, 56, 0, 7, 529, 210, 524, 92, 155, 442,
	17, 84, 523, 5, 518, 383, 517, 516, 61, 258,
	512, 60, 1, 6, 21, 505, 502, 500, 404, 490,
	59, 408, 487, 484, 53, 471, 44, 120, 57, 16,
	163, 13, 468, 51, 159, 460, 11, 10, 14, 452,
	448, 15, 24, 447, 443, 2, 9, 3, 34, 441,
	70, 437, 52, 436, 434, 431, 8, 22, 430, 429,
	35, 18, 412, 26, 23, 411,
}

var yyR1 = [...]int{
	0, 99, 62, 88, 60, 61, 61, 61, 51, 51,
	51, 51, 51, 51, 51, 51, 51, 51, 40, 40,
	41, 41, 31, 31, 31, 39, 102, 45, 43, 43,
	46, 46, 1, 42, 42, 42, 42, 42, 63, 63,
	66, 66, 64, 64, 58, 65, 65, 59, 59, 59,
	59, 35, 35, 35, 35, 22, 23, 16, 5, 5,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 8,
	8, 8, 8, 55, 55, 49, 72, 72, 48, 70,
	71, 71, 69, 69, 69, 68, 68, 68, 67, 67,
	75, 75, 105, 73, 74, 33, 33, 33, 33, 33,
	33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
	33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
	38, 6, 6, 6, 20, 20, 52, 52, 53, 53,
	83, 83, 94, 47, 47, 50, 50, 50, 50, 50,
	93, 93, 92, 90, 89, 91, 91, 91, 34, 34,
	56, 57, 21, 21, 21, 10, 10, 10, 11, 12,
	12, 12, 13, 44, 14, 15, 95, 26, 27, 27,
	30, 30, 28, 28, 28, 28, 28, 29, 29, 29,
	29, 36, 36, 37, 37, 18, 18, 80, 80, 86,
	86, 85, 85, 81, 81, 81, 81, 81, 76, 82,
	82, 77, 77, 84, 84, 78, 87, 87, 79, 98,
	98, 97, 97, 96, 96, 2, 2, 2, 25, 25,
	100, 100, 103, 103, 3, 9, 104, 104, 104, 7,
	7, 7, 24, 24, 101, 101, 101, 54, 17, 17,
	17, 17, 17, 17, 17, 19, 19,
}

var yyR2 = [...]int{
	0, 1, 2, 1, 2, 0, 1, 3, 3, 3,
	3, 3, 1, 3, 3, 3, 1, 1, 3, 3,
	1, 1, 1, 2, 1, 1, 0, 3, 1, 1,
	1, 4, 1, 2, 4, 2, 2, 2, 1, 3,
	1, 3, 1, 2, 1, 2, 3, 1, 1, 4,
	3, 1, 1, 4, 3, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 3, 3, 3, 2, 2, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 1, 3, 3,
	3, 3, 2, 3, 3, 3, 3, 6, 1, 1,
	1, 1, 1, 3, 3, 1, 0, 2, 1, 3,
	0, 1, 0, 1, 2, 1, 1, 3, 1, 3,
	1, 1, 0, 2, 3, 1, 1, 1, 1, 1,
	3, 3, 3, 3, 4, 3, 1, 1, 2, 6,
	6, 4, 4, 5, 4, 5, 4, 3, 1, 1,
	1, 1, 1, 2, 1, 1, 1, 5, 1, 2,
	0, 3, 3, 2, 4, 2, 4, 2, 1, 4,
	3, 3, 2, 2, 4, 1, 2, 1, 1, 1,
	3, 3, 1, 1, 1, 1, 1, 1, 1, 2,
	2, 0, 3, 3, 1, 1, 3, 1, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 0, 3, 3, 2, 1,
	1, 2, 0, 4, 2, 2, 1, 0, 1, 1,
	3, 2, 1, 1, 3, 3, 1, 3, 2, 0,
	2, 1, 3, 3, 2, 1, 1, 1, 1, 1,
	0, 1, 0, 1, 2, 2, 0, 1, 1, 1,
	1, 1, 1, 2, 1, 2, 2, 0, 1, 1,
	1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int{
	-1000, -99, -62, -61, -51, -40, -63, -35, -19, -31,
	-37, -64, 116, -28, -29, -38, 81, 82, -43, 40,
	-32, -65, 87, 83, 85, 66, 84, 41, 65, 46,
	47, -33, -42, -46, -55, -58, -34, -56, -57, -44,
	-36, 113, 92, 64, -50, 52, 54, 61, 71, 69,
	-22, -23, -95, 74, 75, -1, 76, 63, -47, -59,
	-27, -26, -10, -21, -14, 48, 49, 50, -2, -30,
	38, 42, 97, 107, 109, 105, 108, 110, 102, 86,
	44, 45, -100, -101, -7, 111, 95, -24, 88, 53,
	55, 62, 72, 5, 5, -17, 6, 7, 8, 9,
	10, 11, 12, -66, -51, -64, 116, -25, 112, 119,
	91, 90, -43, -32, -35, -37, 40, -38, -28, -29,
	116, 15, 16, 33, 34, 35, 36, 37, 39, 29,
	30, 28, 19, 20, 21, 22, 23, 31, 32, 18,
	17, 13, -8, 24, 26, 25, 27, -58, -28, -29,
	-38, -33, 64, -1, 76, -94, 80, -8, 96, -72,
	-67, -49, -32, -38, -98, -97, -96, -49, 89, -73,
	115, -105, -93, 93, 78, -39, -31, -39, -45, -102,
	-45, -39, -100, -101, -16, 66, -16, -88, -60, -61,
	-73, -70, 115, -73, -70, -68, -67, -97, -49, 91,
	-12, 101, -12, -5, -2, -4, 87, 66, 29, 30,
	28, 19, 20, 22, 23, 24, 25, 26, 27, 21,
	31, 32, 33, 34, 35, 36, 37, 39, 40, -30,
	-51, 95, -24, 88, -39, -39, -39, -39, -43, -75,
	-74, -49, -67, -74, -41, -48, -43, -40, -32, -35,
	-41, -48, -32, -3, -103, 95, -3, -66, -2, 87,
	-5, -69, -68, -67, 66, 5, -17, -25, 112, -32,
	-32, -32, -32, -32, -32, -32, -32, -32, -32, -32,
	-32, -32, -32, -32, -32, -32, -32, -32, -32, -32,
	-32, 96, 112, -25, -92, -83, 29, -32, -9, -103,
	-104, 96, 95, -25, 94, -104, 96, 118, -49, -68,
	-3, -68, -92, -92, -6, -7, 59, -6, -60, -39,
	-60, -100, -90, -89, 70, -18, 26, -88, 51, -100,
	-69, 96, 96, -2, -11, 101, -13, 98, 99, 106,
	-15, 103, -80, 115, -81, -82, -87, -86, -76, -78,
	-84, -79, 87, -77, 28, 89, 96, 5, 117, -3,
	-73, -71, -70, -9, 96, 87, -69, -103, -69, 87,
	51, -60, -82, 87, 114, -49, -96, -49, -3, 94,
	51, -60, 59, -60, 51, -20, -7, 79, 51, -90,
	51, -91, -54, 60, -90, -67, -88, 66, 51, -3,
	-97, -49, -73, -71, -33, -38, -28, -29, -81, -7,
	96, -85, -85, 96, 96, 5, 87, -49, -49, -9,
	14, -9, 29, 96, -52, -53, 68, -54, 60, -53,
	51, -60, 96, -6, 51, -7, 100, -25, 112, -3,
	-86, -87, -76, -78, 87, -77, -49, -32, 51, -31,
	-60, 51, -60, -69, -85, -6, -9, -60, -52,
}

var yyDef = [...]int{
	5, -2, 1, 260, 6, 12, 0, 0, 16, 17,
	0, 38, 0, -2, -2, 0, 285, 286, 22, 0,
	24, 42, -2, 213, 214, -2, 216, 217, 218, 219,
	220, -2, 28, 29, 97, 0, 135, 136, 137, 138,
	139, 116, 249, -2, 147, 0, 0, 26, 26, 260,
	0, 0, 5, 158, 159, 132, -2, 0, 30, 44,
	188, 189, 201, 0, 201, 55, 56, 0, 32, 208,
	0, 207, 195, 196, 197, 192, 193, 194, 204, 257,
	210, 211, 2, 261, 274, 269, 270, 271, 272, 0,
	0, 0, 0, 0, 0, 0, 278, 279, 280, 281,
	282, 283, 284, 262, 262, -2, 0, 0, 122, 0,
	258, 259, 23, 102, 0, 0, 0, 0, -2, -2,
	0, 85, 86, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 109, 110, 111, 112, 43, -2, -2,
	0, 160, 146, 0, 178, 173, 170, 0, 45, 262,
	266, 128, 115, 0, 0, 266, 251, 0, 0, 36,
	262, 0, 148, 170, 170, 0, 25, 0, 5, 0,
	5, 260, 0, 261, 225, 57, 5, 0, 3, 260,
	33, 175, 122, 35, 177, 37, 125, 126, 128, 0,
	0, 0, 0, 237, 58, 59, 255, 256, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 209,
	7, 275, 276, 273, 8, 9, 10, 11, 13, 15,
	130, -2, 0, 14, 18, 81, 20, 21, -2, 0,
	19, 82, 118, 39, 0, 263, 140, 262, -2, -2,
	120, 262, 123, 125, 141, 0, 0, 0, 122, -2,
	-2, 87, 88, 89, 90, 91, 92, 93, 94, 95,
	-2, -2, -2, -2, -2, 103, 104, 105, 106, 262,
	113, 46, 122, 0, 0, 5, 0, 114, 142, 0,
	117, 268, 267, 0, 143, 250, 268, 0, 254, 262,
	145, 133, 0, 0, 5, 161, 162, 5, 0, 0,
	0, 0, 0, 277, 0, 5, 0, 0, 157, 4,
	262, 0, 0, -2, 190, 199, 200, 198, 0, 191,
	203, 205, 206, 237, 0, 232, 232, 236, 239, 246,
	229, 230, 238, 243, 0, 242, 0, 0, 264, -2,
	34, 176, 121, -2, 124, -2, 262, 0, 262, -2,
	172, 182, 0, 238, 265, 129, 252, 253, 144, 180,
	181, 277, 163, 277, 151, 27, 164, 165, 152, 0,
	154, 183, 185, 5, 187, 0, 0, 0, 156, 119,
	127, 129, 31, 174, 160, 0, 221, 222, 262, 228,
	0, 234, 235, 0, 0, 0, 248, 241, -2, -2,
	0, -2, 171, 0, 0, 166, 0, 168, 5, 0,
	153, 186, 0, 5, 155, 226, 202, 0, 122, 227,
	231, 232, 240, 247, 0, 244, 245, 107, 149, 0,
	169, 150, 184, 262, 233, 5, 179, 277, 167,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = true
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := __yyfmt__.Sprintf("syntax error, line %d: unexpected ", currentLineNo) + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			setRoot(yylex, yyDollar[1].node_list)
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = yyDollar[1].node_list
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.body = &Body{Statements: yyDollar[1].node_list}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = yyDollar[1].node_list
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node_list = []Node{}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			switch root(yylex).State.Peek() {
			case InClassBody:
				root(yylex).currentClass.AddStatement(yyDollar[1].node)
				yyVAL.node_list = []Node{}
			case InModuleBody:
				mod := root(yylex).moduleStack.Peek()
				mod.Statements = append(mod.Statements, yyDollar[1].node)
				yyVAL.node_list = []Node{}
			default:
				yyVAL.node_list = []Node{yyDollar[1].node}
			}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			switch root(yylex).State.Peek() {
			case InClassBody:
				root(yylex).currentClass.AddStatement(yyDollar[3].node)
				yyVAL.node_list = []Node{}
			case InModuleBody:
				mod := root(yylex).moduleStack.Peek()
				mod.Statements = append(mod.Statements, yyDollar[3].node)
				yyVAL.node_list = []Node{}
			default:
				yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[3].node)
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[3].node, True: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: &NotExpressionNode{Arg: yyDollar[3].node, lineNo: currentLineNo}, True: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: yyDollar[3].node, Body: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: &NotExpressionNode{Arg: yyDollar[3].node, lineNo: currentLineNo}, Body: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: yyDollar[1].node_list, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: yyDollar[1].node_list, Right: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).inPrivateMethods = true
			yyVAL.node = &NoopNode{}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
		{

			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			operation := &InfixExpressionNode{Left: yyDollar[1].node, Operator: strings.Trim(yyDollar[2].str, "="), Right: yyDollar[3].node, lineNo: currentLineNo}
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &NotExpressionNode{Arg: yyDollar[2].node, lineNo: currentLineNo}
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yylex.(*Lexer).cond.Push(true)
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*Lexer).cond.Pop()
			yyVAL.node = yyDollar[2].node
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := &MethodCall{MethodName: yyDollar[1].str, Args: yyDollar[2].args, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &SuperNode{Args: yyDollar[2].args, Method: root(yylex).currentMethod, Class: root(yylex).currentClass, lineNo: currentLineNo}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", Args: yyDollar[2].args, lineNo: currentLineNo}
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			r := &ReturnNode{Val: yyDollar[2].args, lineNo: currentLineNo}
			root(yylex).AddReturn(r)
			yyVAL.node = r
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node_list = yyDollar[2].node_list
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node_list = yyDollar[2].node_list
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[2].node)
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = []Node{yyDollar[1].node}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[2].node)
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAssignmentNode{
				Composite: yyDollar[1].node,
				Args:      yyDollar[3].args,
				lineNo:    currentLineNo,
			}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Op: yyDollar[2].str, lineNo: currentLineNo}
			yyVAL.node = call
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAssignmentNode{
				Composite: yyDollar[1].node,
				Args:      yyDollar[3].args,
				lineNo:    currentLineNo,
			}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Op: yyDollar[2].str, lineNo: currentLineNo}
			yyVAL.node = call
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).nextConstantType = CLASS
			yyVAL.str = yyDollar[1].str
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).nextConstantType = MODULE
			yyVAL.str = yyDollar[1].str
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if root(yylex).nextConstantType == MODULE {
				root(yylex).PushModule(yyDollar[1].str, currentLineNo)
			} else {
				root(yylex).PushClass(yyDollar[1].str, currentLineNo)
			}
			yyVAL.str = yyDollar[1].str
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			operation := &InfixExpressionNode{Left: yyDollar[1].node, Operator: strings.Trim(yyDollar[2].str, "="), Right: yyDollar[3].node, lineNo: currentLineNo}
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Upper: yyDollar[3].node, Inclusive: true, lineNo: currentLineNo}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Upper: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Inclusive: true, lineNo: currentLineNo}
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, lineNo: currentLineNo}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &NotExpressionNode{Arg: yyDollar[2].node, lineNo: currentLineNo}
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 107:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{
				Condition: yyDollar[1].node,
				True:      Statements{yyDollar[3].node},
				False: &Condition{
					True:       Statements{yyDollar[6].node},
					elseBranch: true,
				},
				lineNo: currentLineNo,
			}
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 116:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = nil
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.args = yyDollar[1].args
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = yyDollar[2].args
		}
	case 120:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = ArgsNode{}
		}
	case 122:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = ArgsNode{}
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = yyDollar[1].args
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			for _, kv := range yyDollar[1].kvs {
				yyVAL.args = append(yyVAL.args, kv)
			}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			for _, kv := range yyDollar[3].kvs {
				yyDollar[1].args = append(yyDollar[1].args, kv)
			}
			yyVAL.args = yyDollar[1].args
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = ArgsNode{yyDollar[1].node}
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].node)
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = []Node{yyDollar[1].node}
		}
	case 132:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			if yyrcvr.Lookahead() == LBRACKETSTART || yyrcvr.Lookahead() == LPARENSTART {
				top := yylex.(*Lexer).cmdArg.Pop()
				yylex.(*Lexer).cmdArg.Push(true)
				yylex.(*Lexer).cmdArg.Push(top)
			} else {
				yylex.(*Lexer).cmdArg.Push(true)
			}
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			/*
			 # call_args can be followed by tLBRACE_ARG (that does cmdarg.push(0) in the lexer)
			 # but the push must be done after cmdarg.pop() in the parser.
			 # So this code does cmdarg.pop() to pop 0 pushed by tLBRACE_ARG,
			 # cmdarg.pop() to pop 1 pushed by command_args,
			 # and cmdarg.push(0) to restore back the flag set by tLBRACE_ARG.
			 last_token = @last_token[0]
			 lookahead = last_token == :tLBRACE_ARG
			 if lookahead
			   top = @lexer.cmdarg.pop
			   @lexer.cmdarg.pop
			   @lexer.cmdarg.push(top)
			 else
			   @lexer.cmdarg.pop
			 end
			*/
			yylex.(*Lexer).cmdArg.Pop()
			yyVAL.args = yyDollar[2].args
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].node)
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ScopeAccessNode{Receiver: yyDollar[1].node, Constant: yyDollar[3].str, lineNo: currentLineNo}
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ArrayNode{Args: yyDollar[2].args, lineNo: currentLineNo}
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &HashNode{Pairs: yyDollar[2].kvs, lineNo: currentLineNo}
		}
	case 144:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			// this is naive, as in theory the source could have non-block locals called "blk".
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", Args: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", lineNo: currentLineNo}
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", lineNo: currentLineNo}
		}
	case 148:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := yyDollar[1].node.(*MethodCall)
			call.SetBlock(yyDollar[2].blk)
			if yylex.(*Lexer).gauntlet && call.MethodName == "gauntlet" {
				lines := strings.Split(yylex.(*Lexer).lastParsedToken.RawBlock, "\n")
				call.RawBlock = strings.Join(lines[1:len(lines)-1], "\n")
				yylex.(*Lexer).gauntlet = false
			}
			yyVAL.node = call
		}
	case 149:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[2].node, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 150:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: &NotExpressionNode{Arg: yyDollar[2].node, lineNo: currentLineNo}, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 151:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: yyDollar[2].node, Body: yyDollar[3].node_list, lineNo: yyDollar[2].node.LineNo()}
		}
	case 152:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: &NotExpressionNode{Arg: yyDollar[2].node, lineNo: yyDollar[2].node.LineNo()}, Body: yyDollar[3].node_list, lineNo: yyDollar[2].node.LineNo()}
		}
	case 153:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &CaseNode{Value: yyDollar[2].node, Whens: yyDollar[4].whens, lineNo: currentLineNo}
		}
	case 154:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &CaseNode{Whens: yyDollar[3].whens, lineNo: currentLineNo}
		}
	case 155:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			root(yylex).currentClass.Superclass = yyDollar[3].str
			yyVAL.node = root(yylex).PopClass()
		}
	case 156:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			r := root(yylex)
			module := r.PopModule()
			if parent := r.moduleStack.Peek(); parent != nil {
				parent.Modules = append(parent.Modules, module)
			} else {
				r.TopLevelModules = append(r.TopLevelModules, module)
			}
			yyVAL.node = module
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[1].meth.Body = yyDollar[2].body
			root(yylex).AddMethod(yyDollar[1].meth)
			root(yylex).State.Pop()
			yyVAL.node = yyDollar[1].meth
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BreakNode{lineNo: currentLineNo}
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &NextNode{lineNo: currentLineNo}
		}
	case 163:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 167:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[2].node, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 169:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &Condition{True: yyDollar[2].node_list, lineNo: currentLineNo, elseBranch: true}
		}
	case 170:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.blk = yyDollar[2].blk
		}
	case 173:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := yyDollar[1].node.(*MethodCall)
			call.SetBlock(yyDollar[2].blk)
			if yylex.(*Lexer).gauntlet && call.MethodName == "gauntlet" {
				lines := strings.Split(yylex.(*Lexer).lastParsedToken.RawBlock, "\n")
				call.RawBlock = strings.Join(lines[1:len(lines)-1], "\n")
				yylex.(*Lexer).gauntlet = false
			}
			yyVAL.node = call
		}
	case 174:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 175:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := &MethodCall{MethodName: yyDollar[1].str, Args: yyDollar[2].args, lineNo: currentLineNo}
			if root(yylex).currentClass != nil {
				root(yylex).currentClass.MethodSet.AddCall(call)
			} else {
				root(yylex).AddCall(call)
			}
			yyVAL.node = call
		}
	case 176:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, Op: yyDollar[2].str, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 177:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &SuperNode{Args: yyDollar[2].args, Method: root(yylex).currentMethod, Class: root(yylex).currentClass, lineNo: currentLineNo}
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &SuperNode{Method: root(yylex).currentMethod, Class: root(yylex).currentClass, lineNo: currentLineNo}
		}
	case 179:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAccessNode{Composite: yyDollar[1].node, Args: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 180:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.blk = yyDollar[2].blk
		}
	case 181:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.blk = yyDollar[2].blk
		}
	case 182:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			blk := &Block{Body: &Body{Statements: yyDollar[2].node_list}, ParamList: NewParamList()}
			for _, p := range yyDollar[1].params {
				blk.AddParam(p)
			}
			yyVAL.blk = blk
		}
	case 183:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.whens = append([]*WhenNode{yyDollar[1].when}, yyDollar[2].whens...)
		}
	case 184:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.when = &WhenNode{Conditions: yyDollar[2].args, Statements: yyDollar[4].node_list, lineNo: currentLineNo}
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.whens = []*WhenNode{}
		}
	case 186:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.whens = []*WhenNode{{Statements: yyDollar[2].node_list, lineNo: currentLineNo}}
		}
	case 190:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			str := root(yylex).StringStack.Pop()
			str.delim = yyDollar[3].str
			yyVAL.node = str
		}
	case 191:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &StringNode{BodySegments: []string{yyDollar[2].str}, Kind: getStringKind(yyDollar[1].str), lineNo: currentLineNo, delim: yyDollar[3].str}
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Push(InString)
			root(yylex).StringStack.Push(&StringNode{Kind: getStringKind(yyDollar[1].str), Interps: make(map[int][]Node), lineNo: currentLineNo})
			yyVAL.str = ""
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Push(InString)
			root(yylex).StringStack.Push(&StringNode{Kind: getStringKind(yyDollar[1].str), Interps: make(map[int][]Node), lineNo: currentLineNo})
			yyVAL.str = ""
		}
	case 197:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Push(InString)
			root(yylex).StringStack.Push(&StringNode{Kind: getStringKind(yyDollar[1].str), Interps: make(map[int][]Node), lineNo: currentLineNo})
			yyVAL.str = ""
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Pop()
			yyVAL.str = yyDollar[1].str
		}
	case 199:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			curr := root(yylex).StringStack.Peek()
			curr.BodySegments = append(curr.BodySegments, yyDollar[2].str)
			yyVAL.str = ""
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 201:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 202:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			curr := root(yylex).StringStack.Peek()
			curr.Interps[len(curr.BodySegments)] = append(curr.Interps[len(curr.BodySegments)], yyDollar[2].node)
			yyVAL.str = ""
		}
	case 203:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			regexp := root(yylex).StringStack.Pop()
			yyVAL.node = regexp
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Push(InString)
			root(yylex).StringStack.Push(&StringNode{Kind: Regexp, Interps: make(map[int][]Node), lineNo: currentLineNo})
			yyVAL.str = ""
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Pop()
			yyVAL.str = ""
		}
	case 206:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			method := NewMethod(yyDollar[2].str, root(yylex))
			method.Private = root(yylex).inPrivateMethods
			method.lineNo = currentLineNo

			for _, p := range yyDollar[3].params {
				if err := method.AddParam(p); err != nil {
					root(yylex).AddError(err)
				}
			}

			root(yylex).State.Push(InMethodDefinition)
			yyVAL.meth = method
			yylex.(*Lexer).resetExpr = true
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &SymbolNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 209:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			var negative Node
			switch x := yyDollar[2].node.(type) {
			case *IntNode:
				x.Val = yyDollar[1].str + x.Val
				negative = x
			case *Float64Node:
				x.Val = yyDollar[1].str + x.Val
				negative = x
			}
			yyVAL.node = negative
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &IntNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &Float64Node{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &IdentNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 213:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			ivar := &IVarNode{Val: yyDollar[1].str, Class: root(yylex).currentClass, lineNo: currentLineNo}
			yyVAL.node = ivar
			cls := root(yylex).currentClass
			if cls != nil {
				cls.AddIVar(ivar.NormalizedVal(), &IVar{Name: ivar.NormalizedVal()})
			}
		}
	case 214:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &GVarNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 215:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ConstantNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 216:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &CVarNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 217:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &NilNode{lineNo: currentLineNo}
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &SelfNode{lineNo: currentLineNo}
		}
	case 219:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BooleanNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 220:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BooleanNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 225:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 226:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 227:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 228:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = yyDollar[1].params
		}
	case 230:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 231:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 232:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 233:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.params = append(append(yyDollar[1].params, yyDollar[3].params...), yyDollar[4].params...)
		}
	case 234:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[2].params...)
		}
	case 235:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[2].params...)
		}
	case 236:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = yyDollar[1].params
		}
	case 237:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 238:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[1].str, Kind: Positional}
		}
	case 239:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 240:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 241:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.param = &Param{Name: strings.Trim(yyDollar[1].str, ":"), Default: yyDollar[2].node, Kind: Keyword}
		}
	case 242:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.param = &Param{Name: strings.Trim(yyDollar[1].str, ":"), Kind: Keyword}
		}
	case 243:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 244:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 245:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[1].str, Default: yyDollar[3].node, Kind: Named}
		}
	case 246:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 247:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 248:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[2].str, Kind: ExplicitBlock}
		}
	case 249:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.kvs = []*KeyValuePair{}
		}
	case 251:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.kvs = []*KeyValuePair{yyDollar[1].kv}
		}
	case 252:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.kvs = append(yyDollar[1].kvs, yyDollar[3].kv)
		}
	case 253:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.kv = &KeyValuePair{Key: yyDollar[1].node, Value: yyDollar[3].node}
		}
	case 254:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.kv = &KeyValuePair{Label: strings.TrimRight(yyDollar[1].str, ":"), Value: yyDollar[2].node}
		}
	case 264:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 265:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 272:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).AddComment(Comment{Text: strings.TrimSpace(yyDollar[1].str), LineNo: currentLineNo})
			yyVAL.str = yyDollar[1].str
		}
	case 273:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			root(yylex).AddComment(Comment{Text: strings.TrimSpace(yyDollar[2].str), LineNo: currentLineNo})
			yyVAL.str = yyDollar[2].str
		}
	case 277:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	}
	goto yystack /* stack new state and value */
}
