// Code generated by goyacc -l -o ruby.go ruby.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import "strings"

func setRoot(yylex yyLexer, nodes []Node) {
	p := yylex.(*Lexer).Root
	for _, n := range nodes {
		p.AddStatement(n)
	}
}

func root(yylex yyLexer) *Root {
	return yylex.(*Lexer).Root
}

type yySymType struct {
	yys       int
	args      ArgsNode
	blk       *Block
	body      *Body
	kv        *KeyValuePair
	kvs       []*KeyValuePair
	meth      *Method
	node      Node
	node_list Statements
	param     *Param
	params    []*Param
	root      *Root
	regexp    string
	when      *WhenNode
	whens     []*WhenNode
	str       string
}

const LOWEST = 57346
const ASSIGN = 57347
const MODASSIGN = 57348
const MULASSIGN = 57349
const ADDASSIGN = 57350
const SUBASSIGN = 57351
const DIVASSIGN = 57352
const LSHIFTASSIGN = 57353
const RSHIFTASSIGN = 57354
const QMARK = 57355
const COLON = 57356
const DOT2 = 57357
const DOT3 = 57358
const LOGICALOR = 57359
const LOGICALAND = 57360
const SPACESHIP = 57361
const EQ = 57362
const NEQ = 57363
const MATCH = 57364
const NOTMATCH = 57365
const GT = 57366
const GTE = 57367
const LT = 57368
const LTE = 57369
const AND = 57370
const PIPE = 57371
const CARET = 57372
const LSHIFT = 57373
const RSHIFT = 57374
const PLUS = 57375
const MINUS = 57376
const ASTERISK = 57377
const SLASH = 57378
const MODULO = 57379
const UNARY_NUM = 57380
const POW = 57381
const BANG = 57382
const NIL = 57383
const SYMBOL = 57384
const STRING = 57385
const INT = 57386
const FLOAT = 57387
const TRUE = 57388
const FALSE = 57389
const CLASS = 57390
const MODULE = 57391
const DEF = 57392
const END = 57393
const IF = 57394
const IF_MOD = 57395
const UNLESS = 57396
const UNLESS_MOD = 57397
const BEGIN = 57398
const RESCUE = 57399
const RESCUE_MOD = 57400
const THEN = 57401
const ELSE = 57402
const WHILE = 57403
const WHILE_MOD = 57404
const RETURN = 57405
const YIELD = 57406
const SELF = 57407
const CONSTANT = 57408
const ENSURE = 57409
const ELSIF = 57410
const CASE = 57411
const WHEN = 57412
const UNTIL = 57413
const UNTIL_MOD = 57414
const FOR = 57415
const BREAK = 57416
const NEXT = 57417
const SUPER = 57418
const ALIAS = 57419
const DO = 57420
const DO_COND = 57421
const DO_BLOCK = 57422
const PRIVATE = 57423
const PROTECTED = 57424
const IN = 57425
const IVAR = 57426
const CVAR = 57427
const GVAR = 57428
const METHODIDENT = 57429
const IDENT = 57430
const COMMENT = 57431
const LABEL = 57432
const ANDDOT = 57433
const DOT = 57434
const LBRACE = 57435
const LBRACEBLOCK = 57436
const RBRACE = 57437
const NEWLINE = 57438
const COMMA = 57439
const STRINGBEG = 57440
const STRINGEND = 57441
const INTERPBEG = 57442
const INTERPEND = 57443
const STRINGBODY = 57444
const REGEXBEG = 57445
const REGEXEND = 57446
const REGEXPOPT = 57447
const RAWSTRINGBEG = 57448
const RAWSTRINGEND = 57449
const WORDSBEG = 57450
const RAWWORDSBEG = 57451
const XSTRINGBEG = 57452
const RAWXSTRINGBEG = 57453
const SEMICOLON = 57454
const LBRACKET = 57455
const LBRACKETSTART = 57456
const RBRACKET = 57457
const LPAREN = 57458
const LPARENSTART = 57459
const RPAREN = 57460
const HASHROCKET = 57461
const SCOPE = 57462

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LOWEST",
	"ASSIGN",
	"MODASSIGN",
	"MULASSIGN",
	"ADDASSIGN",
	"SUBASSIGN",
	"DIVASSIGN",
	"LSHIFTASSIGN",
	"RSHIFTASSIGN",
	"QMARK",
	"COLON",
	"DOT2",
	"DOT3",
	"LOGICALOR",
	"LOGICALAND",
	"SPACESHIP",
	"EQ",
	"NEQ",
	"MATCH",
	"NOTMATCH",
	"GT",
	"GTE",
	"LT",
	"LTE",
	"AND",
	"PIPE",
	"CARET",
	"LSHIFT",
	"RSHIFT",
	"PLUS",
	"MINUS",
	"ASTERISK",
	"SLASH",
	"MODULO",
	"UNARY_NUM",
	"POW",
	"BANG",
	"NIL",
	"SYMBOL",
	"STRING",
	"INT",
	"FLOAT",
	"TRUE",
	"FALSE",
	"CLASS",
	"MODULE",
	"DEF",
	"END",
	"IF",
	"IF_MOD",
	"UNLESS",
	"UNLESS_MOD",
	"BEGIN",
	"RESCUE",
	"RESCUE_MOD",
	"THEN",
	"ELSE",
	"WHILE",
	"WHILE_MOD",
	"RETURN",
	"YIELD",
	"SELF",
	"CONSTANT",
	"ENSURE",
	"ELSIF",
	"CASE",
	"WHEN",
	"UNTIL",
	"UNTIL_MOD",
	"FOR",
	"BREAK",
	"NEXT",
	"SUPER",
	"ALIAS",
	"DO",
	"DO_COND",
	"DO_BLOCK",
	"PRIVATE",
	"PROTECTED",
	"IN",
	"IVAR",
	"CVAR",
	"GVAR",
	"METHODIDENT",
	"IDENT",
	"COMMENT",
	"LABEL",
	"ANDDOT",
	"DOT",
	"LBRACE",
	"LBRACEBLOCK",
	"RBRACE",
	"NEWLINE",
	"COMMA",
	"STRINGBEG",
	"STRINGEND",
	"INTERPBEG",
	"INTERPEND",
	"STRINGBODY",
	"REGEXBEG",
	"REGEXEND",
	"REGEXPOPT",
	"RAWSTRINGBEG",
	"RAWSTRINGEND",
	"WORDSBEG",
	"RAWWORDSBEG",
	"XSTRINGBEG",
	"RAWXSTRINGBEG",
	"SEMICOLON",
	"LBRACKET",
	"LBRACKETSTART",
	"RBRACKET",
	"LPAREN",
	"LPARENSTART",
	"RPAREN",
	"HASHROCKET",
	"SCOPE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 14,
	5, 55,
	6, 237,
	7, 237,
	8, 237,
	9, 237,
	10, 237,
	11, 237,
	12, 237,
	97, 51,
	-2, 235,
	-1, 15,
	5, 56,
	6, 238,
	7, 238,
	8, 238,
	9, 238,
	10, 238,
	11, 238,
	12, 238,
	97, 52,
	-2, 236,
	-1, 21,
	91, 170,
	92, 170,
	113, 170,
	120, 170,
	-2, 116,
	-1, 23,
	38, 269,
	40, 269,
	41, 269,
	42, 269,
	44, 269,
	45, 269,
	46, 269,
	47, 269,
	48, 269,
	49, 269,
	50, 269,
	52, 269,
	54, 269,
	61, 269,
	64, 269,
	65, 269,
	66, 269,
	69, 269,
	71, 269,
	73, 269,
	74, 269,
	75, 269,
	76, 269,
	78, 269,
	84, 269,
	85, 269,
	86, 269,
	87, 269,
	88, 269,
	90, 269,
	93, 269,
	94, 269,
	98, 269,
	103, 269,
	106, 269,
	108, 269,
	109, 269,
	110, 269,
	111, 269,
	114, 269,
	116, 269,
	117, 269,
	-2, 226,
	-1, 26,
	38, 270,
	40, 270,
	41, 270,
	42, 270,
	44, 270,
	45, 270,
	46, 270,
	47, 270,
	48, 270,
	49, 270,
	50, 270,
	52, 270,
	54, 270,
	61, 270,
	64, 270,
	65, 270,
	66, 270,
	69, 270,
	71, 270,
	73, 270,
	74, 270,
	75, 270,
	76, 270,
	78, 270,
	84, 270,
	85, 270,
	86, 270,
	87, 270,
	88, 270,
	90, 270,
	93, 270,
	94, 270,
	98, 270,
	103, 270,
	106, 270,
	108, 270,
	109, 270,
	110, 270,
	111, 270,
	114, 270,
	116, 270,
	117, 270,
	-2, 229,
	-1, 42,
	38, 140,
	40, 140,
	41, 140,
	42, 140,
	44, 140,
	45, 140,
	46, 140,
	47, 140,
	48, 140,
	49, 140,
	50, 140,
	52, 140,
	54, 140,
	61, 140,
	64, 140,
	65, 140,
	66, 140,
	69, 140,
	71, 140,
	73, 140,
	74, 140,
	75, 140,
	76, 140,
	84, 140,
	85, 140,
	86, 140,
	87, 140,
	88, 140,
	90, 140,
	93, 140,
	98, 140,
	103, 140,
	106, 140,
	108, 140,
	109, 140,
	110, 140,
	111, 140,
	114, 140,
	117, 140,
	-2, 154,
	-1, 57,
	38, 140,
	40, 140,
	41, 140,
	42, 140,
	44, 140,
	45, 140,
	46, 140,
	47, 140,
	48, 140,
	49, 140,
	50, 140,
	52, 140,
	54, 140,
	61, 140,
	64, 140,
	65, 140,
	66, 140,
	69, 140,
	71, 140,
	73, 140,
	74, 140,
	75, 140,
	76, 140,
	84, 140,
	85, 140,
	86, 140,
	87, 140,
	88, 140,
	90, 140,
	93, 140,
	98, 140,
	103, 140,
	106, 140,
	108, 140,
	109, 140,
	110, 140,
	111, 140,
	114, 140,
	117, 140,
	-2, 192,
	-1, 111,
	5, 42,
	-2, 44,
	-1, 119,
	5, 55,
	6, 237,
	7, 237,
	8, 237,
	9, 237,
	10, 237,
	11, 237,
	12, 237,
	-2, 235,
	-1, 120,
	5, 56,
	6, 238,
	7, 238,
	8, 238,
	9, 238,
	10, 238,
	11, 238,
	12, 238,
	-2, 236,
	-1, 149,
	91, 235,
	92, 235,
	113, 235,
	120, 235,
	-2, 51,
	-1, 150,
	91, 236,
	92, 236,
	113, 236,
	120, 236,
	-2, 52,
	-1, 191,
	83, 55,
	97, 51,
	-2, 235,
	-1, 192,
	83, 56,
	97, 52,
	-2, 236,
	-1, 248,
	97, 136,
	-2, 139,
	-1, 255,
	97, 123,
	-2, 126,
	-1, 264,
	5, 58,
	97, 54,
	-2, 269,
	-1, 266,
	38, 140,
	40, 140,
	41, 140,
	42, 140,
	44, 140,
	45, 140,
	46, 140,
	47, 140,
	48, 140,
	49, 140,
	50, 140,
	52, 140,
	54, 140,
	61, 140,
	64, 140,
	65, 140,
	66, 140,
	69, 140,
	71, 140,
	73, 140,
	74, 140,
	75, 140,
	76, 140,
	84, 140,
	85, 140,
	86, 140,
	87, 140,
	88, 140,
	90, 140,
	93, 140,
	98, 140,
	103, 140,
	106, 140,
	108, 140,
	109, 140,
	110, 140,
	111, 140,
	114, 140,
	117, 140,
	-2, 62,
	-1, 279,
	15, 0,
	16, 0,
	-2, 91,
	-1, 280,
	15, 0,
	16, 0,
	-2, 92,
	-1, 290,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 104,
	-1, 291,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 106,
	-1, 292,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 107,
	-1, 293,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 108,
	-1, 294,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 109,
	-1, 347,
	1, 128,
	51, 128,
	53, 128,
	55, 128,
	59, 128,
	60, 128,
	62, 128,
	68, 128,
	70, 128,
	72, 128,
	78, 128,
	79, 128,
	89, 128,
	92, 128,
	94, 128,
	95, 128,
	96, 128,
	112, 128,
	118, 128,
	-2, 140,
	-1, 374,
	5, 57,
	97, 53,
	-2, 193,
	-1, 383,
	5, 43,
	-2, 45,
	-1, 384,
	5, 58,
	-2, 269,
	-1, 390,
	5, 54,
	83, 54,
	96, 54,
	97, 54,
	118, 54,
	-2, 269,
	-1, 421,
	83, 58,
	97, 54,
	-2, 269,
	-1, 443,
	97, 137,
	-2, 142,
	-1, 445,
	5, 58,
	-2, 269,
	-1, 455,
	5, 57,
	-2, 193,
	-1, 458,
	5, 53,
	83, 53,
	96, 53,
	97, 53,
	118, 53,
	-2, 193,
	-1, 472,
	83, 57,
	97, 53,
	-2, 193,
	-1, 488,
	5, 57,
	-2, 193,
}

const yyPrivate = 57344

const yyLast = 2065

var yyAct = [...]int{
	20, 461, 85, 309, 326, 173, 436, 156, 9, 462,
	362, 367, 21, 363, 360, 166, 334, 358, 197, 464,
	114, 261, 359, 361, 88, 305, 262, 318, 205, 311,
	83, 379, 84, 169, 382, 152, 176, 177, 170, 410,
	396, 162, 162, 353, 105, 182, 209, 108, 107, 89,
	178, 477, 175, 328, 180, 180, 87, 198, 180, 162,
	438, 163, 11, 152, 108, 107, 270, 251, 109, 479,
	165, 346, 86, 439, 177, 11, 304, 172, 4, 459,
	186, 117, 187, 89, 151, 203, 372, 313, 317, 435,
	87, 201, 110, 106, 184, 162, 255, 260, 375, 180,
	180, 180, 180, 313, 312, 162, 86, 117, 117, 240,
	370, 117, 193, 252, 352, 11, 349, 174, 355, 114,
	345, 301, 200, 279, 280, 281, 282, 283, 284, 285,
	286, 287, 288, 289, 290, 291, 292, 293, 294, 295,
	296, 297, 298, 299, 300, 271, 11, 460, 108, 107,
	401, 315, 117, 117, 117, 117, 117, 257, 257, 308,
	176, 89, 276, 238, 258, 247, 120, 15, 239, 162,
	338, 162, 162, 18, 11, 202, 175, 304, 162, 368,
	15, 273, 327, 11, 327, 207, 329, 351, 352, 150,
	349, 110, 180, 113, 376, 316, 303, 320, 322, 325,
	110, 323, 324, 369, 368, 96, 395, 215, 314, 12,
	259, 441, 240, 154, 43, 342, 333, 192, 187, 337,
	15, 108, 107, 111, 89, 368, 310, 43, 80, 214,
	344, 87, 65, 43, 157, 115, 7, 336, 339, 485,
	330, 369, 332, 277, 11, 117, 11, 86, 267, 7,
	278, 15, 108, 107, 423, 108, 107, 5, 11, 43,
	43, 250, 416, 43, 366, 374, 369, 43, 245, 253,
	253, 70, 336, 202, 302, 260, 260, 104, 162, 15,
	391, 304, 465, 387, 106, 366, 189, 369, 15, 7,
	463, 268, 357, 195, 465, 405, 498, 269, 43, 386,
	378, 212, 373, 162, 43, 43, 43, 43, 43, 43,
	43, 275, 496, 162, 493, 116, 10, 211, 162, 162,
	7, 208, 111, 473, 389, 467, 43, 194, 310, 10,
	394, 256, 256, 398, 409, 43, 424, 162, 266, 162,
	413, 411, 407, 237, 402, 392, 162, 162, 7, 15,
	412, 15, 417, 254, 254, 415, 343, 7, 6, 422,
	420, 434, 398, 15, 393, 429, 388, 437, 11, 10,
	162, 162, 260, 162, 425, 433, 162, 260, 260, 428,
	196, 427, 260, 419, 404, 380, 210, 406, 11, 259,
	455, 11, 129, 458, 444, 143, 43, 43, 43, 307,
	10, 341, 11, 457, 425, 81, 82, 440, 272, 190,
	43, 10, 10, 56, 430, 371, 466, 274, 7, 171,
	7, 327, 95, 470, 472, 94, 474, 183, 10, 1,
	158, 164, 7, 257, 476, 475, 148, 10, 257, 257,
	347, 162, 206, 257, 447, 449, 483, 260, 488, 451,
	482, 486, 484, 310, 260, 260, 310, 260, 492, 481,
	377, 53, 481, 381, 414, 380, 335, 90, 321, 91,
	162, 483, 494, 15, 468, 478, 92, 471, 11, 364,
	162, 11, 306, 161, 167, 356, 93, 310, 365, 500,
	448, 450, 260, 15, 246, 452, 15, 327, 10, 501,
	10, 499, 159, 502, 188, 504, 179, 15, 257, 266,
	271, 310, 10, 22, 489, 90, 2, 91, 69, 432,
	43, 199, 3, 495, 92, 117, 37, 11, 497, 126,
	127, 128, 11, 129, 93, 36, 212, 248, 161, 34,
	43, 44, 7, 43, 59, 253, 33, 212, 38, 32,
	253, 253, 39, 181, 43, 253, 185, 35, 60, 503,
	490, 61, 7, 11, 52, 7, 310, 448, 450, 446,
	452, 383, 212, 119, 14, 51, 7, 63, 328, 453,
	454, 408, 456, 15, 8, 43, 15, 14, 340, 354,
	43, 43, 64, 350, 348, 43, 149, 241, 242, 243,
	244, 62, 213, 263, 0, 490, 266, 256, 89, 0,
	0, 319, 256, 256, 0, 87, 469, 256, 400, 0,
	253, 0, 10, 403, 191, 0, 0, 14, 0, 254,
	43, 86, 15, 43, 254, 254, 0, 15, 0, 254,
	0, 0, 10, 0, 160, 10, 144, 146, 145, 147,
	491, 0, 7, 0, 0, 7, 10, 0, 14, 0,
	43, 0, 204, 124, 125, 126, 127, 128, 15, 129,
	138, 139, 124, 125, 126, 127, 128, 43, 129, 43,
	0, 0, 256, 446, 43, 0, 14, 10, 0, 0,
	331, 0, 10, 10, 0, 14, 0, 10, 249, 249,
	0, 7, 0, 0, 254, 0, 7, 0, 0, 0,
	0, 212, 0, 0, 0, 43, 132, 130, 131, 138,
	139, 124, 125, 126, 127, 128, 0, 129, 0, 0,
	0, 480, 10, 0, 0, 10, 0, 7, 144, 146,
	145, 147, 132, 130, 131, 138, 139, 124, 125, 126,
	127, 128, 0, 129, 0, 397, 14, 0, 14, 0,
	167, 399, 10, 97, 98, 99, 100, 101, 102, 103,
	14, 0, 0, 0, 204, 204, 0, 0, 0, 161,
	0, 10, 0, 0, 0, 0, 10, 0, 426, 167,
	219, 220, 227, 221, 222, 223, 224, 225, 226, 218,
	216, 217, 228, 229, 230, 231, 232, 233, 234, 0,
	235, 236, 442, 443, 0, 0, 0, 10, 426, 71,
	0, 19, 28, 72, 0, 81, 82, 30, 31, 66,
	67, 68, 0, 45, 0, 46, 0, 215, 0, 0,
	0, 0, 47, 0, 58, 42, 29, 26, 0, 0,
	49, 0, 48, 0, 50, 54, 55, 57, 80, 214,
	0, 0, 16, 17, 0, 24, 27, 25, 80, 23,
	89, 0, 0, 0, 41, 0, 0, 239, 0, 73,
	14, 0, 0, 487, 79, 0, 0, 76, 0, 74,
	77, 75, 78, 0, 0, 40, 0, 0, 13, 0,
	14, 0, 0, 14, 0, 0, 0, 0, 0, 0,
	0, 0, 397, 0, 14, 130, 131, 138, 139, 124,
	125, 126, 127, 128, 0, 129, 431, 71, 0, 19,
	28, 72, 0, 81, 82, 30, 31, 66, 67, 68,
	418, 45, 0, 46, 0, 0, 0, 0, 0, 0,
	47, 0, 58, 42, 29, 26, 0, 0, 49, 0,
	48, 0, 50, 54, 55, 57, 0, 0, 0, 0,
	0, 0, 0, 24, 27, 25, 80, 23, 89, 0,
	0, 0, 41, 0, 0, 87, 0, 73, 0, 0,
	14, 0, 79, 14, 0, 76, 0, 74, 77, 75,
	78, 86, 0, 40, 0, 0, 121, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 71, 0, 19, 28, 72, 0, 81, 82,
	30, 31, 66, 67, 68, 0, 45, 0, 46, 14,
	0, 0, 0, 0, 14, 47, 0, 58, 42, 29,
	26, 0, 0, 49, 0, 48, 0, 50, 54, 55,
	57, 0, 0, 0, 0, 16, 17, 0, 24, 27,
	25, 80, 23, 0, 0, 14, 0, 41, 0, 0,
	0, 0, 73, 0, 0, 0, 0, 79, 0, 0,
	76, 0, 74, 77, 75, 78, 0, 0, 40, 0,
	71, 13, 19, 28, 72, 0, 81, 82, 30, 31,
	66, 67, 68, 0, 45, 0, 46, 0, 0, 0,
	0, 0, 0, 47, 0, 58, 42, 29, 26, 0,
	0, 49, 0, 48, 0, 50, 54, 55, 57, 0,
	0, 0, 0, 16, 17, 0, 24, 27, 25, 80,
	23, 0, 0, 0, 0, 41, 0, 0, 0, 0,
	73, 0, 0, 0, 0, 79, 0, 0, 76, 0,
	74, 77, 75, 78, 0, 0, 40, 0, 71, 112,
	118, 28, 72, 0, 81, 82, 30, 31, 66, 67,
	68, 0, 45, 0, 46, 0, 0, 0, 0, 0,
	0, 47, 0, 0, 153, 29, 26, 0, 0, 49,
	0, 48, 0, 50, 54, 55, 155, 0, 0, 0,
	0, 0, 0, 0, 24, 27, 25, 80, 23, 0,
	168, 0, 0, 41, 0, 0, 271, 0, 73, 0,
	0, 0, 0, 79, 0, 0, 76, 0, 74, 77,
	75, 78, 0, 0, 40, 0, 71, 121, 118, 28,
	72, 0, 81, 82, 30, 31, 66, 67, 68, 0,
	45, 0, 46, 0, 0, 0, 0, 0, 0, 47,
	0, 0, 153, 29, 26, 0, 0, 49, 0, 48,
	0, 50, 54, 55, 155, 0, 0, 0, 0, 0,
	0, 0, 24, 27, 25, 80, 23, 0, 168, 0,
	0, 41, 0, 0, 0, 0, 73, 0, 0, 0,
	0, 79, 0, 0, 76, 0, 74, 77, 75, 78,
	0, 0, 40, 0, 71, 121, 19, 28, 72, 0,
	81, 82, 30, 31, 66, 67, 68, 0, 45, 0,
	46, 0, 0, 0, 0, 0, 0, 47, 0, 58,
	42, 29, 26, 0, 0, 49, 0, 48, 0, 50,
	54, 55, 57, 0, 0, 0, 0, 0, 0, 0,
	24, 27, 25, 80, 23, 0, 0, 0, 0, 41,
	0, 0, 0, 0, 73, 0, 0, 0, 0, 79,
	0, 0, 76, 0, 74, 77, 75, 78, 0, 0,
	40, 0, 71, 121, 118, 28, 72, 0, 81, 82,
	30, 31, 66, 67, 68, 0, 45, 0, 46, 0,
	0, 0, 0, 0, 0, 47, 0, 58, 42, 29,
	26, 0, 0, 49, 0, 48, 0, 50, 54, 55,
	57, 0, 0, 0, 0, 0, 0, 0, 24, 27,
	25, 80, 23, 0, 0, 0, 0, 41, 0, 0,
	0, 0, 73, 0, 0, 0, 0, 79, 0, 0,
	76, 0, 74, 77, 75, 78, 0, 0, 40, 0,
	71, 121, 118, 28, 72, 0, 81, 82, 30, 31,
	66, 67, 68, 0, 45, 0, 46, 0, 0, 0,
	0, 0, 0, 47, 0, 0, 153, 29, 26, 0,
	0, 49, 0, 48, 0, 50, 54, 55, 155, 0,
	0, 0, 0, 0, 0, 0, 24, 27, 25, 80,
	23, 0, 0, 0, 0, 41, 0, 0, 0, 0,
	73, 0, 0, 0, 0, 79, 0, 0, 76, 0,
	74, 77, 75, 78, 71, 0, 40, 28, 72, 121,
	81, 82, 30, 31, 66, 67, 68, 0, 45, 0,
	46, 0, 0, 0, 0, 0, 0, 47, 0, 0,
	153, 29, 26, 0, 0, 49, 0, 48, 0, 50,
	54, 55, 155, 0, 0, 0, 0, 0, 0, 0,
	24, 27, 25, 80, 23, 0, 0, 0, 0, 41,
	0, 0, 0, 0, 73, 0, 0, 0, 0, 79,
	0, 0, 76, 0, 74, 77, 75, 78, 71, 0,
	40, 28, 72, 121, 81, 82, 30, 31, 66, 67,
	68, 0, 45, 0, 46, 0, 0, 0, 0, 0,
	0, 47, 0, 0, 153, 29, 26, 0, 0, 49,
	0, 48, 0, 50, 54, 55, 155, 0, 0, 0,
	0, 0, 0, 0, 24, 27, 25, 80, 23, 0,
	0, 0, 0, 41, 0, 0, 0, 0, 73, 0,
	0, 0, 0, 79, 0, 0, 76, 0, 74, 77,
	75, 78, 0, 0, 40, 0, 142, 13, 122, 123,
	141, 140, 133, 134, 135, 136, 137, 144, 146, 145,
	147, 132, 130, 131, 138, 139, 124, 125, 126, 127,
	128, 0, 129, 219, 220, 227, 221, 222, 223, 224,
	225, 226, 218, 216, 217, 228, 229, 230, 231, 232,
	233, 234, 0, 235, 236, 0, 219, 220, 227, 221,
	222, 223, 224, 225, 226, 218, 216, 217, 228, 229,
	230, 231, 232, 233, 234, 0, 235, 236, 0, 0,
	265, 0, 0, 0, 0, 0, 0, 0, 0, 271,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 80, 445, 215, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 80, 421, 219, 220, 227, 221,
	222, 223, 224, 225, 226, 218, 216, 217, 228, 229,
	230, 231, 232, 233, 234, 0, 235, 236, 0, 219,
	220, 227, 221, 222, 223, 224, 225, 226, 218, 216,
	217, 228, 229, 230, 231, 232, 233, 234, 0, 235,
	236, 0, 0, 385, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 80, 384, 215, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 80, 390, 219,
	220, 227, 221, 222, 223, 224, 225, 226, 218, 216,
	217, 228, 229, 230, 231, 232, 233, 234, 0, 235,
	236, 142, 0, 122, 123, 141, 140, 133, 134, 135,
	136, 137, 144, 146, 145, 147, 132, 130, 131, 138,
	139, 124, 125, 126, 127, 128, 265, 129, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 80, 264, 141,
	140, 133, 134, 135, 136, 137, 144, 146, 145, 147,
	132, 130, 131, 138, 139, 124, 125, 126, 127, 128,
	0, 129, 140, 133, 134, 135, 136, 137, 144, 146,
	145, 147, 132, 130, 131, 138, 139, 124, 125, 126,
	127, 128, 0, 129, 133, 134, 135, 136, 137, 144,
	146, 145, 147, 132, 130, 131, 138, 139, 124, 125,
	126, 127, 128, 0, 129,
}

var yyPact = [...]int{
	984, -1000, -1000, 135, 462, -1000, 420, 417, -1000, -1000,
	757, 164, -1000, 1062, -1000, -1000, -1000, -1000, -1000, 1374,
	1938, -1000, 1526, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 154, -1000, 622, -1000, -1000, -1000, -1000, -1000,
	1452, 1218, -78, -42, 82, 1296, 1296, -1000, -1000, 889,
	1600, 227, 227, 984, -1000, -1000, 25, -79, 1218, 93,
	-1000, -1000, -1000, -56, -1000, -1000, -1000, -1000, 771, -1000,
	-1000, 361, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 781, -1000, -1000, -1000, -1000, -1000,
	1296, 1296, 1296, 1296, 1374, 1374, 1374, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 1218, 1910, 225, -1000, -1000, 49,
	414, -1000, 1062, -1000, -1000, 412, 757, 130, 1452, -1000,
	-1000, 984, 1452, 1452, 1452, 1452, 1452, 1452, 1452, 1452,
	1452, 1452, 1452, 1452, 1452, 1452, 1452, 1452, 1452, 1452,
	1452, 1452, 1452, 1452, -1000, -1000, -1000, -1000, 24, -1000,
	-1000, 161, -1000, -78, -42, -79, -1000, 370, 1452, 49,
	7, -1000, 1938, 130, 56, -9, -1000, -92, 1452, -1000,
	1140, 1218, -1000, -1000, -1000, 370, 370, 1218, -1000, -6,
	-1000, -6, 984, 1296, 984, 135, 167, 72, 136, -1000,
	-1000, -1000, -1000, 57, 375, -1000, 984, 305, -1000, 135,
	-1000, -1000, -1000, -1000, 23, -26, -92, 141, 88, -64,
	14, 176, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 462, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 13,
	-1000, -1000, -1000, -1000, -1000, 1938, 410, -27, -1000, -1000,
	1938, 49, -1000, 1, 757, 757, -1000, -79, 757, -1000,
	-84, -1000, -1000, 49, 1452, 1452, 1817, 1218, 217, 1982,
	1982, 494, 494, 353, 353, 353, 353, 639, 639, 886,
	714, 714, 714, 714, 714, 630, 630, 2025, 2004, 1703,
	688, -1000, 1218, 1840, 214, 294, 984, 118, 688, -1000,
	-75, -1000, 1452, -1000, 1817, -1000, -1000, 1218, 1452, -1000,
	49, -1000, -1000, 55, 293, 49, 984, 236, -1000, 984,
	291, -40, 290, 167, 289, 202, 1452, -1000, 1218, 1747,
	984, 188, 285, -1000, -1000, 1218, 1218, -79, -1000, -1000,
	-1000, -1000, 1526, -1000, -1000, -1000, -1000, 197, 135, -8,
	-37, -1000, -1000, -1000, -24, -1000, 402, -1000, 123, 1452,
	1452, 1374, 1218, 1724, 757, 1218, 1374, 1374, -1000, -1000,
	-1000, 1374, -1000, -1000, 757, 757, 49, 757, 389, 49,
	-1000, -1000, -1000, -1000, 50, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 222, -1000, 234, -1000, -1000, -1000,
	-1000, -1000, 274, -1000, -1000, -1000, 984, -1000, 519, 984,
	49, -1000, 272, 135, -1000, -26, -92, 154, 82, -50,
	-44, -1000, -1000, 49, -1000, 197, -1000, -1000, 151, 113,
	1452, -1000, -1000, -1000, 49, 757, 1374, -1000, -1000, -1000,
	-1000, -1000, -1000, 1452, 1452, 757, 1452, 1452, -1000, -1000,
	118, 263, -1000, 1296, -1000, 984, 261, -1000, -1000, 1452,
	984, 245, -1000, -1000, -1000, -1000, -1000, -1000, 771, 1218,
	-1000, -1000, -37, -1000, -1000, 402, -1000, -1000, 757, -1000,
	-1000, 1452, 1938, -1000, -6, -1000, -1000, -1000, -1000, 49,
	-1000, 984, -1000, 222, -1000,
}

var yyPgo = [...]int{
	0, 213, 232, 297, 602, 248, 4, 2, 395, 3,
	601, 594, 321, 593, 592, 589, 327, 194, 588, 584,
	581, 577, 575, 564, 24, 44, 561, 558, 573, 166,
	271, 8, 0, 12, 557, 235, 552, 315, 61, 506,
	257, 67, 549, 173, 548, 45, 546, 544, 113, 442,
	541, 78, 1, 9, 19, 539, 535, 526, 413, 518,
	57, 521, 516, 358, 209, 513, 68, 504, 603, 26,
	21, 117, 31, 502, 33, 165, 494, 10, 11, 13,
	488, 485, 17, 22, 482, 479, 6, 23, 14, 18,
	466, 16, 464, 25, 5, 7, 461, 15, 28, 431,
	429, 30, 32, 427, 66, 29, 419,
}

var yyR1 = [...]int{
	0, 100, 62, 89, 60, 61, 61, 61, 51, 51,
	51, 51, 51, 51, 51, 51, 51, 51, 40, 40,
	40, 40, 40, 40, 41, 41, 31, 31, 31, 39,
	103, 45, 43, 43, 46, 46, 1, 42, 42, 42,
	42, 42, 63, 63, 66, 66, 64, 64, 58, 65,
	65, 59, 59, 59, 59, 35, 35, 35, 35, 22,
	23, 16, 5, 5, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 8, 8, 8,
	8, 55, 55, 49, 73, 73, 48, 71, 72, 72,
	70, 70, 70, 69, 69, 69, 68, 68, 76, 76,
	106, 74, 75, 33, 33, 33, 33, 33, 33, 33,
	33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
	33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
	38, 6, 6, 6, 20, 20, 52, 52, 53, 53,
	67, 67, 84, 84, 95, 47, 47, 47, 47, 50,
	50, 50, 50, 50, 94, 94, 93, 91, 90, 92,
	92, 92, 34, 34, 56, 57, 21, 21, 21, 10,
	10, 10, 11, 12, 12, 12, 13, 44, 14, 15,
	96, 26, 27, 27, 30, 30, 28, 28, 28, 28,
	28, 29, 29, 29, 29, 36, 36, 37, 37, 18,
	18, 81, 81, 87, 87, 86, 86, 82, 82, 82,
	82, 82, 77, 83, 83, 78, 78, 85, 85, 79,
	88, 88, 80, 99, 99, 98, 98, 97, 97, 2,
	2, 2, 25, 25, 101, 101, 104, 104, 3, 9,
	105, 105, 105, 7, 7, 7, 24, 102, 102, 102,
	54, 17, 17, 17, 17, 17, 17, 17, 19, 19,
}

var yyR2 = [...]int{
	0, 1, 2, 1, 2, 0, 1, 3, 3, 3,
	3, 3, 1, 3, 3, 3, 1, 1, 3, 3,
	6, 5, 5, 5, 1, 1, 1, 2, 1, 1,
	0, 3, 1, 1, 1, 4, 1, 2, 4, 2,
	2, 2, 1, 3, 1, 3, 1, 2, 1, 2,
	3, 1, 1, 4, 3, 1, 1, 4, 3, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 3, 3, 6, 5, 5,
	5, 3, 3, 2, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 1, 3, 3, 3, 3,
	2, 3, 3, 3, 3, 6, 1, 1, 1, 1,
	1, 3, 3, 1, 0, 2, 1, 3, 0, 1,
	0, 1, 2, 1, 1, 3, 1, 3, 1, 1,
	0, 2, 3, 1, 1, 1, 1, 1, 3, 3,
	3, 3, 4, 3, 1, 2, 1, 2, 6, 6,
	4, 4, 5, 4, 6, 5, 4, 3, 1, 1,
	1, 1, 1, 2, 1, 1, 1, 5, 1, 2,
	1, 1, 0, 3, 3, 2, 4, 5, 5, 2,
	4, 2, 1, 4, 3, 3, 2, 2, 4, 1,
	2, 1, 1, 1, 3, 3, 1, 1, 1, 1,
	1, 1, 1, 2, 2, 0, 3, 3, 1, 1,
	3, 1, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
	3, 3, 2, 1, 1, 2, 0, 4, 2, 2,
	1, 0, 1, 1, 3, 2, 1, 1, 3, 3,
	1, 3, 2, 0, 2, 1, 3, 3, 2, 1,
	1, 1, 1, 1, 0, 1, 0, 1, 2, 2,
	0, 1, 1, 1, 1, 1, 1, 1, 2, 2,
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int{
	-1000, -100, -62, -61, -51, -40, -63, -35, -19, -31,
	-37, -38, -64, 117, -28, -29, 81, 82, -43, 40,
	-32, -33, -65, 88, 84, 86, 66, 85, 41, 65,
	46, 47, -42, -46, -55, -34, -56, -57, -44, -36,
	114, 93, 64, -1, -50, 52, 54, 61, 71, 69,
	73, -22, -23, -96, 74, 75, -58, 76, 63, -47,
	-27, -26, -10, -21, -14, -2, 48, 49, 50, -59,
	-30, 38, 42, 98, 108, 110, 106, 109, 111, 103,
	87, 44, 45, -101, -102, -7, 112, 96, -24, 89,
	53, 55, 62, 72, 5, 5, -17, 6, 7, 8,
	9, 10, 11, 12, 113, -25, 120, 92, 91, -66,
	-51, -64, 117, -43, -32, -35, -37, -38, 40, -28,
	-29, 117, 15, 16, 33, 34, 35, 36, 37, 39,
	29, 30, 28, 19, 20, 21, 22, 23, 31, 32,
	18, 17, 13, -8, 24, 26, 25, 27, -58, -28,
	-29, -38, -33, 64, -1, 76, -95, 80, -8, -73,
	-68, -49, -32, -38, -99, -98, -97, -49, 90, -74,
	116, -106, -74, -94, -71, 94, 78, 116, -94, -39,
	-31, -39, -45, -103, -45, -39, -101, -102, -67, -35,
	-63, -28, -29, -38, -16, 66, -16, -89, -60, -61,
	97, -74, -71, -69, -68, -98, -49, 92, -12, 102,
	-12, -5, -2, -4, 88, 66, 29, 30, 28, 19,
	20, 22, 23, 24, 25, 26, 27, 21, 31, 32,
	33, 34, 35, 36, 37, 39, 40, -30, -51, 96,
	-24, -39, -39, -39, -39, -43, -76, -75, -49, -68,
	-75, -41, -48, -43, -40, -32, -35, -38, -41, -48,
	-32, -70, -69, -68, 88, 66, -2, -5, 66, -3,
	-104, 96, -3, -66, 5, -17, -25, 113, 120, -32,
	-32, -32, -32, -32, -32, -32, -32, -32, -32, -32,
	-32, -32, -32, -32, -32, -32, -32, -32, -32, -32,
	-32, 97, 113, -25, 120, -93, -84, 29, -32, -9,
	-104, -105, 97, 96, -25, 95, -105, 97, 119, -49,
	-69, -3, -69, -93, -93, -70, -6, -7, 59, -6,
	-60, -39, -60, -101, -91, -90, 70, 83, 113, -25,
	-18, 26, -89, 51, -101, 97, 97, -2, -11, 102,
	-13, 99, 100, 107, -15, 104, -81, 116, -82, -83,
	-88, -87, -77, -79, -85, -80, 88, -78, 28, 90,
	97, 5, 113, -25, -9, 97, -17, -17, -74, -72,
	-71, -17, 118, -3, 88, 66, -70, 66, -104, -70,
	88, 66, 51, -60, -83, 88, 115, -49, -97, -49,
	-3, 95, 51, -3, -60, 59, -60, 51, -20, -7,
	79, 51, -91, 51, -92, -54, 60, -91, -68, -45,
	-70, 88, -89, 66, 51, -98, -49, -74, -72, -33,
	-38, -28, -29, -82, -7, 97, -86, -86, 97, 97,
	5, 88, -49, -49, -70, 88, -17, -41, -48, -41,
	-48, -41, -48, -17, -17, -9, -17, 14, -9, 29,
	97, -52, -53, 68, -54, 60, -53, 51, -60, 97,
	-6, -60, -9, 51, -7, -95, -94, 101, -25, 113,
	-3, -87, -88, -77, -79, 88, -78, -49, -9, -41,
	-48, -17, -32, 51, -31, -60, 51, -60, 51, -70,
	-86, -6, -9, -60, -52,
}

var yyDef = [...]int{
	5, -2, 1, 274, 6, 12, 0, 0, 16, 17,
	0, 0, 42, 0, -2, -2, 298, 299, 26, 0,
	28, -2, 46, -2, 227, 228, -2, 230, 231, 232,
	233, 234, 32, 33, 105, 143, 144, 145, 146, 147,
	124, 263, -2, 140, 156, 0, 0, 30, 30, 274,
	0, 0, 0, 5, 168, 169, 0, -2, 0, 34,
	202, 203, 215, 0, 215, 36, 59, 60, 0, 48,
	222, 0, 221, 209, 210, 211, 206, 207, 208, 218,
	271, 224, 225, 2, 275, 287, 283, 284, 285, 286,
	0, 0, 0, 0, 0, 0, 0, 291, 292, 293,
	294, 295, 296, 297, 130, 0, 0, 272, 273, 276,
	276, -2, 0, 27, 110, 0, 0, 0, 0, -2,
	-2, 0, 93, 94, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 117, 118, 119, 120, 47, -2,
	-2, 0, 170, 154, 0, 192, 185, 182, 0, 276,
	280, 136, 123, 0, 0, 280, 265, 0, 0, 40,
	276, 0, 37, 155, 189, 182, 182, 130, 157, 0,
	29, 0, 5, 0, 5, 274, 0, 275, 0, 180,
	181, -2, -2, 0, 239, 61, 5, 0, 3, 274,
	49, 39, 191, 41, 133, 134, 136, 0, 0, 0,
	0, 251, 62, 63, 269, 270, 64, 65, 66, 67,
	68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
	78, 79, 80, 81, 82, 83, 84, 223, 7, 288,
	289, 8, 9, 10, 11, 13, 15, 138, -2, 0,
	14, 18, 85, 24, 25, -2, 0, 0, 19, 86,
	126, 276, 131, 133, -2, 270, -2, 128, 149, 43,
	0, 277, 148, 276, 0, 0, 0, 130, 0, -2,
	-2, 95, 96, 97, 98, 99, 100, 101, 102, 103,
	-2, -2, -2, -2, -2, 111, 112, 113, 114, 276,
	121, 50, 130, 0, 0, 0, 5, 0, 122, 150,
	0, 125, 282, 281, 0, 151, 264, 282, 0, 268,
	276, 153, 141, 0, 0, 276, 5, 171, 172, 5,
	0, 0, 0, 0, 0, 290, 0, 30, 130, 0,
	5, 0, 0, 167, 4, 0, 0, -2, 204, 213,
	214, 212, 0, 205, 217, 219, 220, 251, 0, 246,
	246, 250, 253, 260, 243, 244, 252, 257, 0, 256,
	0, 0, 130, 0, -2, 132, 0, 0, 38, 190,
	129, 0, 278, -2, -2, 270, 276, 149, 0, 276,
	-2, 149, 184, 196, 0, 252, 279, 137, 266, 267,
	152, 194, 195, 127, 290, 173, 290, 160, 31, 174,
	175, 161, 0, 163, 197, 199, 5, 201, 0, 5,
	276, -2, 0, 0, 166, 135, 137, 35, 186, 170,
	0, 235, 236, 276, 242, 0, 248, 249, 0, 0,
	0, 262, 255, -2, 276, -2, 0, 21, 88, 22,
	89, 23, 90, 0, 0, -2, 0, 0, -2, 183,
	0, 0, 176, 0, 178, 5, 0, 162, 200, 0,
	5, 0, -2, 165, 240, 188, 187, 216, 0, 130,
	241, 245, 246, 254, 261, 0, 258, 259, -2, 20,
	87, 0, 115, 158, 0, 179, 159, 198, 164, 276,
	247, 5, 193, 290, 177,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = true
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := __yyfmt__.Sprintf("syntax error, line %d: unexpected ", currentLineNo) + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			setRoot(yylex, yyDollar[1].node_list)
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = yyDollar[1].node_list
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.body = &Body{Statements: yyDollar[1].node_list}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = yyDollar[1].node_list
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node_list = []Node{}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			switch root(yylex).State.Peek() {
			case InClassBody:
				root(yylex).currentClass.AddStatement(yyDollar[1].node)
				yyVAL.node_list = []Node{}
			case InModuleBody:
				mod := root(yylex).moduleStack.Peek()
				mod.Statements = append(mod.Statements, yyDollar[1].node)
				yyVAL.node_list = []Node{}
			default:
				yyVAL.node_list = []Node{yyDollar[1].node}
			}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			switch root(yylex).State.Peek() {
			case InClassBody:
				root(yylex).currentClass.AddStatement(yyDollar[3].node)
				yyVAL.node_list = []Node{}
			case InModuleBody:
				mod := root(yylex).moduleStack.Peek()
				mod.Statements = append(mod.Statements, yyDollar[3].node)
				yyVAL.node_list = []Node{}
			default:
				yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[3].node)
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[3].node, True: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: &NotExpressionNode{Arg: yyDollar[3].node, lineNo: currentLineNo}, True: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: yyDollar[3].node, Body: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: &NotExpressionNode{Arg: yyDollar[3].node, lineNo: currentLineNo}, Body: Statements{yyDollar[1].node}, lineNo: currentLineNo}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: yyDollar[1].node_list, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: yyDollar[1].node_list, Right: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).inPrivateMethods = true
			yyVAL.node = &NoopNode{}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
		{

			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			operation := &InfixExpressionNode{Left: yyDollar[1].node, Operator: strings.Trim(yyDollar[2].str, "="), Right: yyDollar[3].node, lineNo: currentLineNo}
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 20:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			access := &BracketAccessNode{Composite: yyDollar[1].node, Args: yyDollar[3].args, lineNo: currentLineNo}
			operation := &InfixExpressionNode{Left: access, Operator: strings.Trim(yyDollar[5].str, "="), Right: yyDollar[6].node, lineNo: currentLineNo}
			assignment := &BracketAssignmentNode{
				Composite: yyDollar[1].node,
				Args:      yyDollar[3].args,
				lineNo:    currentLineNo,
			}
			yyVAL.node = &AssignmentNode{Left: []Node{assignment}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 21:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, lineNo: currentLineNo}
			operation := &InfixExpressionNode{Left: call, Operator: strings.Trim(yyDollar[4].str, "="), Right: yyDollar[5].node, lineNo: currentLineNo}
			assignment := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, lineNo: currentLineNo}
			yyVAL.node = &AssignmentNode{Left: []Node{assignment}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			noop := &NoopNode{currentLineNo}
			root(yylex).AddError(NewParseError(&NoopNode{currentLineNo}, "Tried to modify constant '%s'. In Ruby this only warns, but thanos forbids it.", yyDollar[3].str).Terminal())
			yyVAL.node = noop
		}
	case 23:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			noop := &NoopNode{currentLineNo}
			root(yylex).AddError(NewParseError(&NoopNode{currentLineNo}, "Tried to modify constant '%s'. In Ruby this only warns, but thanos forbids it.", yyDollar[3].str).Terminal())
			yyVAL.node = noop
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &NotExpressionNode{Arg: yyDollar[2].node, lineNo: currentLineNo}
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yylex.(*Lexer).cond.Push(true)
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*Lexer).cond.Pop()
			yyVAL.node = yyDollar[2].node
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := &MethodCall{MethodName: yyDollar[1].str, Args: yyDollar[2].args, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &SuperNode{Args: yyDollar[2].args, Method: root(yylex).currentMethod, Class: root(yylex).currentClass, lineNo: currentLineNo}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", Args: yyDollar[2].args, lineNo: currentLineNo}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			r := &ReturnNode{Val: yyDollar[2].args, lineNo: currentLineNo}
			root(yylex).AddReturn(r)
			yyVAL.node = r
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node_list = yyDollar[2].node_list
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node_list = yyDollar[2].node_list
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[2].node)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node_list = []Node{yyDollar[1].node}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node_list = append(yyDollar[1].node_list, yyDollar[2].node)
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAssignmentNode{
				Composite: yyDollar[1].node,
				Args:      yyDollar[3].args,
				lineNo:    currentLineNo,
			}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Op: yyDollar[2].str, lineNo: currentLineNo}
			yyVAL.node = call
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAssignmentNode{
				Composite: yyDollar[1].node,
				Args:      yyDollar[3].args,
				lineNo:    currentLineNo,
			}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Op: yyDollar[2].str, lineNo: currentLineNo}
			yyVAL.node = call
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).nextConstantType = CLASS
			yyVAL.str = yyDollar[1].str
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).nextConstantType = MODULE
			yyVAL.str = yyDollar[1].str
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if root(yylex).nextConstantType == MODULE {
				root(yylex).PushModule(yyDollar[1].str, currentLineNo)
			} else {
				root(yylex).PushClass(yyDollar[1].str, currentLineNo)
			}
			yyVAL.str = yyDollar[1].str
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{yyDollar[3].node}, lineNo: currentLineNo}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			operation := &InfixExpressionNode{Left: yyDollar[1].node, Operator: strings.Trim(yyDollar[2].str, "="), Right: yyDollar[3].node, lineNo: currentLineNo}
			yyVAL.node = &AssignmentNode{Left: []Node{yyDollar[1].node}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 87:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			access := &BracketAccessNode{Composite: yyDollar[1].node, Args: yyDollar[3].args, lineNo: currentLineNo}
			operation := &InfixExpressionNode{Left: access, Operator: strings.Trim(yyDollar[5].str, "="), Right: yyDollar[6].node, lineNo: currentLineNo}
			assignment := &BracketAssignmentNode{
				Composite: yyDollar[1].node,
				Args:      yyDollar[3].args,
				lineNo:    currentLineNo,
			}
			yyVAL.node = &AssignmentNode{Left: []Node{assignment}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 88:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, lineNo: currentLineNo}
			operation := &InfixExpressionNode{Left: call, Operator: strings.Trim(yyDollar[4].str, "="), Right: yyDollar[5].node, lineNo: currentLineNo}
			assignment := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, lineNo: currentLineNo}
			yyVAL.node = &AssignmentNode{Left: []Node{assignment}, Right: []Node{operation}, OpAssignment: true, lineNo: currentLineNo}
		}
	case 89:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			noop := &NoopNode{currentLineNo}
			root(yylex).AddError(NewParseError(&NoopNode{currentLineNo}, "Tried to modify constant '%s'. In Ruby this only warns, but thanos forbids it.", yyDollar[3].str).Terminal())
			yyVAL.node = noop
		}
	case 90:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			noop := &NoopNode{currentLineNo}
			root(yylex).AddError(NewParseError(&NoopNode{currentLineNo}, "Tried to modify constant '%s'. In Ruby this only warns, but thanos forbids it.", yyDollar[3].str).Terminal())
			yyVAL.node = noop
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Upper: yyDollar[3].node, Inclusive: true, lineNo: currentLineNo}
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Upper: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, Inclusive: true, lineNo: currentLineNo}
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &RangeNode{Lower: yyDollar[1].node, lineNo: currentLineNo}
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &NotExpressionNode{Arg: yyDollar[2].node, lineNo: currentLineNo}
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 115:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{
				Condition: yyDollar[1].node,
				True:      Statements{yyDollar[3].node},
				False: &Condition{
					True:       Statements{yyDollar[6].node},
					elseBranch: true,
				},
				lineNo: currentLineNo,
			}
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &InfixExpressionNode{Left: yyDollar[1].node, Operator: yyDollar[2].str, Right: yyDollar[3].node, lineNo: currentLineNo}
		}
	case 124:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = nil
		}
	case 125:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.args = yyDollar[1].args
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = yyDollar[2].args
		}
	case 128:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = ArgsNode{}
		}
	case 130:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.args = ArgsNode{}
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = yyDollar[1].args
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			for _, kv := range yyDollar[1].kvs {
				yyVAL.args = append(yyVAL.args, kv)
			}
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			for _, kv := range yyDollar[3].kvs {
				yyDollar[1].args = append(yyDollar[1].args, kv)
			}
			yyVAL.args = yyDollar[1].args
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = ArgsNode{yyDollar[1].node}
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].node)
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.args = []Node{yyDollar[1].node}
		}
	case 140:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			if yyrcvr.Lookahead() == LBRACKETSTART || yyrcvr.Lookahead() == LPARENSTART {
				top := yylex.(*Lexer).cmdArg.Pop()
				yylex.(*Lexer).cmdArg.Push(true)
				yylex.(*Lexer).cmdArg.Push(top)
			} else {
				yylex.(*Lexer).cmdArg.Push(true)
			}
		}
	case 141:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			/*
			 # call_args can be followed by tLBRACE_ARG (that does cmdarg.push(0) in the lexer)
			 # but the push must be done after cmdarg.pop() in the parser.
			 # So this code does cmdarg.pop() to pop 0 pushed by tLBRACE_ARG,
			 # cmdarg.pop() to pop 1 pushed by command_args,
			 # and cmdarg.push(0) to restore back the flag set by tLBRACE_ARG.
			 last_token = @last_token[0]
			 lookahead = last_token == :tLBRACE_ARG
			 if lookahead
			   top = @lexer.cmdarg.pop
			   @lexer.cmdarg.pop
			   @lexer.cmdarg.push(top)
			 else
			   @lexer.cmdarg.pop
			 end
			*/
			yylex.(*Lexer).cmdArg.Pop()
			yyVAL.args = yyDollar[2].args
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].node)
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ScopeAccessNode{Receiver: yyDollar[1].node, Constant: yyDollar[3].str, lineNo: currentLineNo}
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ArrayNode{Args: yyDollar[2].args, lineNo: currentLineNo}
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &HashNode{Pairs: yyDollar[2].kvs, lineNo: currentLineNo}
		}
	case 152:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			// this is naive, as in theory the source could have non-block locals called "blk".
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", Args: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 153:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", lineNo: currentLineNo}
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).currentMethod.AddParam(&Param{Name: "blk", Kind: ExplicitBlock})
			yyVAL.node = &MethodCall{Receiver: &IdentNode{Val: "blk"}, MethodName: "call", lineNo: currentLineNo}
		}
	case 155:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := &MethodCall{MethodName: yyDollar[1].str, lineNo: currentLineNo}
			call.SetBlock(yyDollar[2].blk)
			yyVAL.node = call
		}
	case 157:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := yyDollar[1].node.(*MethodCall)
			call.SetBlock(yyDollar[2].blk)
			if yylex.(*Lexer).gauntlet && call.MethodName == "gauntlet" {
				lines := strings.Split(yylex.(*Lexer).lastParsedToken.RawBlock, "\n")
				call.RawBlock = strings.Join(lines[1:len(lines)-1], "\n")
				yylex.(*Lexer).gauntlet = false
			}
			yyVAL.node = call
		}
	case 158:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[2].node, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 159:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: &NotExpressionNode{Arg: yyDollar[2].node, lineNo: currentLineNo}, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 160:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: yyDollar[2].node, Body: yyDollar[3].node_list, lineNo: yyDollar[2].node.LineNo()}
		}
	case 161:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &WhileNode{Condition: &NotExpressionNode{Arg: yyDollar[2].node, lineNo: yyDollar[2].node.LineNo()}, Body: yyDollar[3].node_list, lineNo: yyDollar[2].node.LineNo()}
		}
	case 162:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &CaseNode{Value: yyDollar[2].node, Whens: yyDollar[4].whens, lineNo: currentLineNo}
		}
	case 163:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &CaseNode{Whens: yyDollar[3].whens, lineNo: currentLineNo}
		}
	case 164:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ForInNode{For: yyDollar[2].node_list, In: yyDollar[4].node, Body: yyDollar[5].node_list, lineNo: currentLineNo}
		}
	case 165:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			root(yylex).currentClass.Superclass = yyDollar[3].str
			yyVAL.node = root(yylex).PopClass()
		}
	case 166:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			r := root(yylex)
			module := r.PopModule()
			if parent := r.moduleStack.Peek(); parent != nil {
				parent.Modules = append(parent.Modules, module)
			} else {
				r.TopLevelModules = append(r.TopLevelModules, module)
			}
			yyVAL.node = module
		}
	case 167:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[1].meth.Body = yyDollar[2].body
			root(yylex).AddMethod(yyDollar[1].meth)
			root(yylex).State.Pop()
			yyVAL.node = yyDollar[1].meth
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BreakNode{lineNo: currentLineNo}
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &NextNode{lineNo: currentLineNo}
		}
	case 173:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 177:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &Condition{Condition: yyDollar[2].node, True: yyDollar[4].node_list, False: yyDollar[5].node, lineNo: currentLineNo}
		}
	case 179:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &Condition{True: yyDollar[2].node_list, lineNo: currentLineNo, elseBranch: true}
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node_list = []Node{yyDollar[1].node}
		}
	case 182:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 183:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 184:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.blk = yyDollar[2].blk
		}
	case 185:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := yyDollar[1].node.(*MethodCall)
			call.SetBlock(yyDollar[2].blk)
			if yylex.(*Lexer).gauntlet && call.MethodName == "gauntlet" {
				lines := strings.Split(yylex.(*Lexer).lastParsedToken.RawBlock, "\n")
				call.RawBlock = strings.Join(lines[1:len(lines)-1], "\n")
				yylex.(*Lexer).gauntlet = false
			}
			yyVAL.node = call
		}
	case 186:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 187:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, lineNo: currentLineNo}
			call.SetBlock(yyDollar[5].blk)
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 188:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, lineNo: currentLineNo}
			call.SetBlock(yyDollar[5].blk)
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 189:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			call := &MethodCall{MethodName: yyDollar[1].str, Args: yyDollar[2].args, lineNo: currentLineNo}
			if root(yylex).currentClass != nil {
				root(yylex).currentClass.MethodSet.AddCall(call)
			} else {
				root(yylex).AddCall(call)
			}
			yyVAL.node = call
		}
	case 190:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			call := &MethodCall{Receiver: yyDollar[1].node, MethodName: yyDollar[3].str, Args: yyDollar[4].args, Op: yyDollar[2].str, lineNo: currentLineNo}
			root(yylex).AddCall(call)
			yyVAL.node = call
		}
	case 191:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &SuperNode{Args: yyDollar[2].args, Method: root(yylex).currentMethod, Class: root(yylex).currentClass, lineNo: currentLineNo}
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &SuperNode{Method: root(yylex).currentMethod, Class: root(yylex).currentClass, lineNo: currentLineNo}
		}
	case 193:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &BracketAccessNode{Composite: yyDollar[1].node, Args: yyDollar[3].args, lineNo: currentLineNo}
		}
	case 194:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.blk = yyDollar[2].blk
		}
	case 195:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.blk = yyDollar[2].blk
		}
	case 196:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			blk := &Block{Body: &Body{Statements: yyDollar[2].node_list}, ParamList: NewParamList()}
			for _, p := range yyDollar[1].params {
				blk.AddParam(p)
			}
			yyVAL.blk = blk
		}
	case 197:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.whens = append([]*WhenNode{yyDollar[1].when}, yyDollar[2].whens...)
		}
	case 198:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.when = &WhenNode{Conditions: yyDollar[2].args, Statements: yyDollar[4].node_list, lineNo: currentLineNo}
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.whens = []*WhenNode{}
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.whens = []*WhenNode{{Statements: yyDollar[2].node_list, lineNo: currentLineNo}}
		}
	case 204:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			str := root(yylex).StringStack.Pop()
			str.delim = yyDollar[3].str
			yyVAL.node = str
		}
	case 205:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &StringNode{BodySegments: []string{yyDollar[2].str}, Kind: getStringKind(yyDollar[1].str), lineNo: currentLineNo, delim: yyDollar[3].str}
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Push(InString)
			root(yylex).StringStack.Push(&StringNode{Kind: getStringKind(yyDollar[1].str), Interps: make(map[int][]Node), lineNo: currentLineNo})
			yyVAL.str = ""
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Push(InString)
			root(yylex).StringStack.Push(&StringNode{Kind: getStringKind(yyDollar[1].str), Interps: make(map[int][]Node), lineNo: currentLineNo})
			yyVAL.str = ""
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Push(InString)
			root(yylex).StringStack.Push(&StringNode{Kind: getStringKind(yyDollar[1].str), Interps: make(map[int][]Node), lineNo: currentLineNo})
			yyVAL.str = ""
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Pop()
			yyVAL.str = yyDollar[1].str
		}
	case 213:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			curr := root(yylex).StringStack.Peek()
			curr.BodySegments = append(curr.BodySegments, yyDollar[2].str)
			yyVAL.str = ""
		}
	case 214:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 215:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 216:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			curr := root(yylex).StringStack.Peek()
			curr.Interps[len(curr.BodySegments)] = append(curr.Interps[len(curr.BodySegments)], yyDollar[2].node)
			yyVAL.str = ""
		}
	case 217:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			regexp := root(yylex).StringStack.Pop()
			yyVAL.node = regexp
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Push(InString)
			root(yylex).StringStack.Push(&StringNode{Kind: Regexp, Interps: make(map[int][]Node), lineNo: currentLineNo})
			yyVAL.str = ""
		}
	case 219:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).State.Pop()
			yyVAL.str = ""
		}
	case 220:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			method := NewMethod(yyDollar[2].str, root(yylex))
			method.Private = root(yylex).inPrivateMethods
			method.lineNo = currentLineNo

			for _, p := range yyDollar[3].params {
				if err := method.AddParam(p); err != nil {
					root(yylex).AddError(err)
				}
			}

			root(yylex).State.Push(InMethodDefinition)
			yyVAL.meth = method
			yylex.(*Lexer).resetExpr = true
		}
	case 221:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &SymbolNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 223:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			var negative Node
			switch x := yyDollar[2].node.(type) {
			case *IntNode:
				x.Val = yyDollar[1].str + x.Val
				negative = x
			case *Float64Node:
				x.Val = yyDollar[1].str + x.Val
				negative = x
			}
			yyVAL.node = negative
		}
	case 224:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &IntNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &Float64Node{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 226:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &IdentNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			ivar := &IVarNode{Val: yyDollar[1].str, Class: root(yylex).currentClass, lineNo: currentLineNo}
			yyVAL.node = ivar
			cls := root(yylex).currentClass
			if cls != nil {
				cls.AddIVar(ivar.NormalizedVal(), &IVar{Name: ivar.NormalizedVal()})
			}
		}
	case 228:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &GVarNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ConstantNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 230:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &CVarNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 231:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &NilNode{lineNo: currentLineNo}
		}
	case 232:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &SelfNode{lineNo: currentLineNo}
		}
	case 233:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BooleanNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 234:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BooleanNode{Val: yyDollar[1].str, lineNo: currentLineNo}
		}
	case 239:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.str = ""
		}
	case 240:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 241:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 242:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = yyDollar[1].params
		}
	case 244:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 245:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = yyDollar[2].params
		}
	case 246:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 247:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.params = append(append(yyDollar[1].params, yyDollar[3].params...), yyDollar[4].params...)
		}
	case 248:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[2].params...)
		}
	case 249:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[2].params...)
		}
	case 250:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = yyDollar[1].params
		}
	case 251:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.params = []*Param{}
		}
	case 252:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[1].str, Kind: Positional}
		}
	case 253:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 254:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 255:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.param = &Param{Name: strings.Trim(yyDollar[1].str, ":"), Default: yyDollar[2].node, Kind: Keyword}
		}
	case 256:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.param = &Param{Name: strings.Trim(yyDollar[1].str, ":"), Kind: Keyword}
		}
	case 257:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 258:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 259:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[1].str, Default: yyDollar[3].node, Kind: Named}
		}
	case 260:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []*Param{yyDollar[1].param}
		}
	case 261:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 262:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.param = &Param{Name: yyDollar[2].str, Kind: ExplicitBlock}
		}
	case 263:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.kvs = []*KeyValuePair{}
		}
	case 265:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.kvs = []*KeyValuePair{yyDollar[1].kv}
		}
	case 266:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.kvs = append(yyDollar[1].kvs, yyDollar[3].kv)
		}
	case 267:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.kv = &KeyValuePair{Key: yyDollar[1].node, Value: yyDollar[3].node}
		}
	case 268:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.kv = &KeyValuePair{Label: strings.TrimRight(yyDollar[1].str, ":"), Value: yyDollar[2].node}
		}
	case 278:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 279:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.str = yyDollar[2].str
		}
	case 286:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			root(yylex).AddComment(Comment{Text: strings.TrimSpace(yyDollar[1].str), LineNo: currentLineNo})
			yyVAL.str = yyDollar[1].str
		}
	case 290:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	}
	goto yystack /* stack new state and value */
}
